## **6. Técnicas de Amostragem de Dados: Amostragem Polarizada por Densidade**

#### Autor: Tony Esaú de Oliveira
Universidade Federal do Cariri - UFCA

#### **O que é amostragem?**

O processo de amostragem é formalmente definido como a seleção de um subconjunto (denominado amostra) de membros de uma população ou conjunto de dados original, com o propósito de derivar estimativas e tirar conclusões sobre essa população utilizando apenas os membros selecionados. Matematicamente, se $N$ representa o número total de elementos na população e $n$ o tamanho da amostra $S$, o processo seleciona elementos de tal forma que $n<N$

#### **Característica Essencial de uma Amostragem:**

Para que a amostragem seja válida, a amostra deve ser **representativa**, o que significa que ela deve conservar as características e propriedades consideradas importantes do conjunto original. Assim, os resultados obtidos pela análise da amostra devem ser muito semelhantes aos que seriam encontrados caso toda a população fosse processada

#### **Importância**

A importância da amostragem reside na viabilização da análise de dados em larga escala através de diversos benefícios:

- **Redução do Volume e Custo Computacional**: A mineração de dados e a análise de grandes volumes são processos caros e complexos. A amostragem funciona como uma técnica de redução de dados que permite que algoritmos operem de forma mais eficiente e rápida, diminuindo a complexidade de tempo;

- **Economia de Recursos**: Em muitas aplicações, coletar dados de toda uma população é irrealista ou impossível devido aos altos custos financeiros, de tempo, materiais e de mão de obra. A amostragem permite obter informações confiáveis com gastos significativamente menores;

- **Agilidade e Tempestividade**: Por ser um processo mais rápido, a amostragem permite que os resultados sejam publicados e utilizados de forma oportuna. Em ciência de dados, uma resposta aproximada e rápida é frequentemente preferível a uma resposta exata que demore muito tempo para ser processada;

- **Melhoria na Qualidade dos Dados**: Como o volume de dados a ser tratado é menor, os investigadores podem ser mais cuidadosos na coleta, treinamento e supervisão, o que muitas vezes resulta em dados mais precisos do que os obtidos em um censo completo, que pode estar sujeito a erros administrativos e de coleta em larga escala;

- **Necessidade Técnica**: Em casos onde a medição exige a destruição da unidade de observação (como testes de laboratório), a amostragem é o único meio de obter informações sem eliminar toda a população.

---

### **Credit Card Fraud Detection**

##### **Visão geral**

O dataset **Credit Card Fraud Detection** contém transações realizadas com cartões de crédito por clientes europeus em setembro de 2013. O objetivo principal é detectar **transações fraudulentas**.

##### **Estrutura dos dados**

* Total de instâncias: **284.315 transações.**
* Número de fraudes: **492.**
* Dataset altamente **Desbalanceado.**


##### **Atributos**

* `Time`
  Tempo (em segundos) desde a primeira transação no dataset.

* `Amount`
  Valor da transação.

* `V1` a `V28`
  Variáveis numéricas resultantes de uma transformação **PCA (Principal Component Analysis)**.

* `Class`

  * `0`: Transação normal..
  * `1`: Fraude

##### **Observações importantes**

* Os dados foram **anonimizados** (PCA), então não há informações semânticas diretas sobre as features.
* Não requer limpeza significativa, está pronto para uso.

---

 #### **Amostragem por Reservatório**

A Amostragem Polarizada por Densidade é uma técnica de redução de dados onde a probabilidade de um elemento ser selecionado para a amostra depende da densidade local de sua vizinhança. Diferente da amostragem uniforme, ela busca equilibrar a representatividade de agrupamentos (clusters) com tamanhos ou densidades muito distintos, realizando o *oversampling* (superamostragem) de regiões esparsas e o *undersampling* (subamostragem) de regiões densas.

Considere um conjunto de dados com $N$ pontos onde se deseja extrair uma amostra de tamanho $n$. O processo segue esta lógica geral:
- Estimação de Densidade: Para cada elemento $x$, calcula-se uma função de densidade $f(x)$ que quantifica a concentração de pontos em sua vizinhança local;
- Probabilidade de Inclusão: A probabilidade $P(x)$ de um ponto ser incluído na amostra é definida como: 
    - $P(x) = \frac{f^a(x)}{\sum_{i=1}^{N} f^a(x_i)}$, onde:
        - $\sum_{i=1}^{N} f^a(x)$ para garantir que a soma das probabilidades seja coerente;
        - $a$ é um parâmetro de ajuste. Quando $a<0$, o algoritmo privilegia pontos em regiões de baixa densidade (bias negativo), aumentando a chance de selecionar elementos de grupos raros. Se $a > 0$, favorece regiões de alta densidade.

O algoritmo mais simples, Density-Based Sampling (DBS), funciona da seguinte maneira 
1. **Cálculo da Densidade Local** ($f(x)$): Para cada ponto do conjunto de dados, você deve estimar a densidade de sua vizinhança. Isso é feito medindo a distância (geralmente a Euclidiana) entre os pontos. Pode-se usar:
    - $\text{Kernel Density Estimation}$ (KDE): Soma-se a influência de todos os pontos próximos usando uma função de kernel (como a Gaussiana);
    - $\text{K-vizinhos mais próximos}$: A densidade é estimada com base na distância média para os $k$ vizinhos mais próximos.

2. **Definição do Parâmetro de Ajuste** ($a$): Você define um expoente a que determina o "viés" da amostragem:
- Para priorizar regiões de baixa densidade (capturar grupos raros), use um $a$ negativo (ex: $−0,25$ ou $−0,5$), isso garante que pontos em áreas esparsas tenham uma probabilidade maior de seleção.

3. **Cálculo da Probabilidade de Inclusão** [$P(x) = \frac{f^a(x)}{\sum_{i=1}^{N} f^a(x_i)}$].

4. **Sorteio e Seleção**: Para cada ponto, gera-se um número aleatório. Se esse número for menor ou igual a $P(x)$, o ponto é adicionado à amostra final.

---

In [2]:
import pandas as pd
import numpy as np

In [3]:
dados = pd.read_csv('Conjuntos_Dados/credit_card_fraud.csv')

In [4]:
dados.head(10)

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0
5,2.0,-0.425966,0.960523,1.141109,-0.168252,0.420987,-0.029728,0.476201,0.260314,-0.568671,...,-0.208254,-0.559825,-0.026398,-0.371427,-0.232794,0.105915,0.253844,0.081080,3.67,0
6,4.0,1.229658,0.141004,0.045371,1.202613,0.191881,0.272708,-0.005159,0.081213,0.464960,...,-0.167716,-0.270710,-0.154104,-0.780055,0.750137,-0.257237,0.034507,0.005168,4.99,0
7,7.0,-0.644269,1.417964,1.074380,-0.492199,0.948934,0.428118,1.120631,-3.807864,0.615375,...,1.943465,-1.015455,0.057504,-0.649709,-0.415267,-0.051634,-1.206921,-1.085339,40.80,0
8,7.0,-0.894286,0.286157,-0.113192,-0.271526,2.669599,3.721818,0.370145,0.851084,-0.392048,...,-0.073425,-0.268092,-0.204233,1.011592,0.373205,-0.384157,0.011747,0.142404,93.20,0
9,9.0,-0.338262,1.119593,1.044367,-0.222187,0.499361,-0.246761,0.651583,0.069539,-0.736727,...,-0.246914,-0.633753,-0.120794,-0.385050,-0.069733,0.094199,0.246219,0.083076,3.68,0

In [5]:
dados.shape

(284807, 31)

In [6]:
dados[dados['Class'] == 1].shape

(492, 31)

In [7]:
dados[dados['Class'] == 0].shape

(284315, 31)

Ou seja, o conjuntos de dados é totalmente desbalanceado quanto às duas classes (fraude ou não). Como provavelmente iremos utilizar esse Conjunto de Dados para treinamento de um modelo de classificação, devemos ter obrigatoriamente uma parte da amostra relacionada à classe fraude. A amostragem Polarizada por Densidade é uma ótima escolha num Conjunto de Dados como esse.

##### **Cálculo de tamanho**

Para esse exemplo, iremos calcular o tamanho da amostra a partir do Intervalo de Confiança para Proporção:

$$\hat{p} \pm Z \cdot \sqrt{\frac{\hat{p}(1 - \hat{p})}{n}}$$

Em que:

- $\hat{p}$: Proporção observada na amostra (estimativa da proporção real).

- $Z$: Valor crítico da distribuição normal padrão (depende do nível de confiança).

- $n$: Tamanho da amostra.

- $\hat{p}(1 - \hat{p})$: Variância da proporção.

- $\sqrt{\frac{\hat{p}(1 - \hat{p})}{n}}$: Erro padrão da proporção (mede a variabilidade da estimativa).

Vamos calcular considerando $99\%$ de confiança e erro menor igual a $2\%$. Para isso devemos garantir que o erro padrão de proporção seja menor ou igual a $2\%$. Para isso, consideremos o pior caso para o denominador $\hat{p}(1-\hat{p})$, isto é, quando ele é maximizado. Um estudo quadrático simples, nos apontará que esse valor é $0,5$. Vamos rearranjar a fórmula sabendo disso:

$$Z \cdot \sqrt{\frac{\hat{p}(1 - \hat{p})}{n}} \leq 0,02$$
$$ \frac{1}{Z}Z \cdot \sqrt{\frac{\hat{p}(1 - \hat{p})}{n}} \leq \frac{1}{Z} 0,02$$
$$\sqrt{\frac{\hat{p}(1 - \hat{p})}{n}} \leq \frac{0,02}{Z}$$
$$\frac{\sqrt{(0,5)^2}}{\sqrt{n}} \leq \frac{0,02}{Z}$$
$$\frac{0,5}{\sqrt{n}} \leq \frac{0,02}{Z}$$
$$\frac{\sqrt{n}} {0,5} \geq \frac{Z}{0,02}$$
$$ \sqrt{n} \geq \frac{Z}{0,02} \cdot 0,5$$
$$ n \geq (\frac{Z}{0,04})^2$$

Calculando:

In [18]:
from scipy.stats import norm
import math

Z = norm.ppf(0.99)

n = math.ceil((Z/0.04)**2)
n

3383

 #### **Amostragem Polarizada por Densidade (DBS)**

In [ ]:
# Tomando as colunas de dados gerados pelo PCA.
features = [col for col in dados.columns if col.startswith('V')]
X = dados[features]
X

,V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,...,V19,V20,V21,V22,V23,V24,V25,V26,V27,V28
0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,0.090794,...,0.403993,0.251412,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053
1,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,-0.166974,...,-0.145783,-0.069083,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724
2,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,0.207643,...,-2.261857,0.524980,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752
3,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,-0.054952,...,-1.232622,-0.208038,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458
4,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,0.753074,...,0.803487,0.408542,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
284802,-11.881118,10.071785,-9.834783,-2.066656,-5.364473,-2.606837,-4.918215,7.305334,1.914428,4.356170,...,-0.682920,1.475829,0.213454,0.111864,1.014480,-0.509348,1.436807,0.250034,0.943651,0.823731
284803,-0.732789,-0.055080,2.035030,-0.738589,0.868229,1.058415,0.024330,0.294869,0.584800,-0.975926,...,-1.545556,0.059616,0.214205,0.924384,0.012463,-1.016226,-0.606624,-0.395255,0.068472,-0.053527
284804,1.919565,-0.301254,-3.249640,-0.557828,2.630515,3.031260,-0.296827,0.708417,0.432454,-0.484782,...,-0.577252,0.001396,0.232045,0.578229,-0.037501,0.640134,0.265745,-0.087371,0.004455,-0.026561
284805,-0.240440,0.530483,0.702510,0.689799,-0.377961,0.623708,-0.686180,0.679145,0.392087,-0.399126,...,2.897849,0.127434,0.265245,0.800049,-0.163298,0.123205,-0.569159,0.546668,0.108821,0.104533
284806,-0.533413,-0.189733,0.703337,-0.506271,-0.012546,-0.649617,1.577006,-0.414650,0.486180,-0.915427,...,-0.256117,0.382948,0.261057,0.643078,0.376777,0.008797,-0.473649,-0.818267,-0.002415,0.013649

Vamos usar os $k$ vizinhos mais próximos.

In [ ]:
from sklearn.neighbors import NearestNeighbors
import numpy as np

# O k pode ser ajustado dependendo do tamanho do dataset e da dimensionalidade, o interessante seria realizar testes para encontrar o melhor valor.
k = 10

# Calcula as distâncias para os k vizinhos mais próximos de cada ponto.
nbrs = NearestNeighbors(n_neighbors=k).fit(X)

distancias, _ = nbrs.kneighbors(X)

"""
    - Média das distâncias aos vizinhos.
    - A adição de um pequeno valor (1e-8) evita divisão por zero.
    - A densidade é inversamente proporcional à média das distâncias: pontos em regiões mais densas terão distâncias menores, resultando em pesos maiores.
"""

densidade = 1 / (distancias.mean(axis=1) + 1e-8)

In [37]:
a = -100  # Penalizar as amostras em regiões de alta densidade.
"""
    - O valor de a pode ser ajustado para controlar o grau de polarização: valores mais negativos aumentam a penalização para regiões densas, enquanto
    valores próximos de zero reduzem essa penalização.
"""
peso = densidade ** a

In [38]:
# Normaliza os pesos para obter probabilidades.
P = peso / peso.sum()

In [39]:
# Amostra os índices dos dados com base nas probabilidades calculadas.
indices = np.random.choice(len(dados), size=n, replace=False, p=P)

# Seleciona as amostras correspondentes aos índices amostrados.
amostra = dados.iloc[indices]
amostra

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
274771,166198.0,-35.548539,-31.850484,-48.325589,15.304184,-113.743307,73.301626,120.589494,-27.347360,-3.872425,...,-21.620120,5.712303,-1.581098,4.584549,4.554683,3.415636,31.612198,-15.430084,25691.16,0
39769,39954.0,-56.407510,-72.715728,-6.605265,16.491217,34.801666,-26.160506,-19.399981,-1.501300,6.967698,...,-6.266878,-1.272167,7.893082,0.767805,5.376595,0.163672,-8.358317,33.847808,1201.83,0
58465,48401.0,-36.802320,-63.344698,-20.645794,16.715537,-20.672064,7.694002,24.956587,-4.730111,-2.687312,...,11.455313,-10.933144,-17.173665,1.180700,-7.025783,-2.534330,-3.602479,3.450224,19656.53,0
65423,51575.0,-14.904340,12.793880,-7.888739,0.512373,-7.661829,16.614054,-31.764946,-73.216718,-6.290730,...,-34.830382,10.503090,4.245073,-1.412813,-0.730374,0.133557,-0.394370,0.942177,500.00,0
151296,95286.0,-34.549296,-60.464618,-21.340854,16.875344,-19.229075,6.335259,24.422716,-4.964566,0.188912,...,11.502580,-9.499423,-16.513186,0.744341,-7.081325,-2.604551,-3.550963,3.250802,18910.00,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13199,23232.0,-3.307725,-3.886072,2.078416,4.625695,-2.635005,2.790797,1.987734,0.324236,1.185478,...,0.830204,0.800622,2.699441,-0.027044,0.226492,0.416932,-0.218033,0.251463,1133.14,0
169342,119650.0,-8.448148,5.804749,-1.740417,-0.829886,0.226014,-0.638010,2.669137,-2.348052,6.163114,...,-0.858005,0.095950,-0.613999,-0.101205,1.651356,-0.790712,-4.106196,-1.282670,12.53,0
63772,50862.0,-7.260160,-0.748718,-4.235954,2.197864,-1.154121,-0.504497,-1.798552,2.899145,-0.081777,...,-0.031561,-0.370800,-2.122943,-1.117761,-0.338351,-0.203432,0.605844,-0.550336,1.00,0
6549,7935.0,-3.571625,3.766904,0.537258,0.165960,0.725576,1.866493,-1.434563,-11.077980,3.006796,...,8.852711,-2.808630,0.920416,-0.669967,-0.037939,-0.476512,-0.906298,-0.958159,7.46,0
169341,119650.0,-8.448148,5.804749,-1.740417,-0.829886,0.226014,-0.638010,2.669137,-2.348052,6.163114,...,-0.858005,0.095950,-0.613999,-0.101205,1.651356,-0.790712,-4.106196,-1.282670,12.53,0

Vamos observar a proporção:

In [40]:
dados['Class'].value_counts(normalize=True)

Class
0    0.998273
1    0.001727
Name: proportion, dtype: float64

In [41]:
amostra['Class'].value_counts(normalize=True)

Class
0    0.91812
1    0.08188
Name: proportion, dtype: float64

Usando $a=-100$ temos um valor razoável, mas perceba que o alto desbalanceamento dificulta. Vale ressaltar também que nesse método a penalização pode facilitar a entrada de *outliers* de todas as classes, pois não faz distinção entre elas, o método leva em consideração simplesmente a densidade e geometria.

Podemos aplicar essa ideia selecionando todos elementos da classe minoritária e aplicar o método na outra classe:

In [42]:
fraudes = dados[dados['Class'] == 1]

In [47]:
normais = dados[dados['Class'] == 0]

In [ ]:
features = [col for col in dados.columns if col.startswith('V')]
X_normais = normais[features]

# Calcula densidade.
nbrs = NearestNeighbors(n_neighbors=11).fit(X_normais)
dist, _ = nbrs.kneighbors(X_normais)
dist = dist[:, 1:]

dens = 1 / (dist.mean(axis=1) + 1e-8)

In [53]:
# Aplica viés.
a = -1
peso = dens ** a
P = peso / peso.sum()

# Amostra.
n_normais = n - len(fraudes)
idx = np.random.choice(len(normais), size=n_normais, replace=False, p=P)

amostra_normais = normais.iloc[idx]
amostra_1 = pd.concat([fraudes, amostra_normais], ignore_index=True)
amostra_1

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,406.0,-2.312227,1.951992,-1.609851,3.997906,-0.522188,-1.426545,-2.537387,1.391657,-2.770089,...,0.517232,-0.035049,-0.465211,0.320198,0.044519,0.177840,0.261145,-0.143276,0.00,1
1,472.0,-3.043541,-3.157307,1.088463,2.288644,1.359805,-1.064823,0.325574,-0.067794,-0.270953,...,0.661696,0.435477,1.375966,-0.293803,0.279798,-0.145362,-0.252773,0.035764,529.00,1
2,4462.0,-2.303350,1.759247,-0.359745,2.330243,-0.821628,-0.075788,0.562320,-0.399147,-0.238253,...,-0.294166,-0.932391,0.172726,-0.087330,-0.156114,-0.542628,0.039566,-0.153029,239.93,1
3,6986.0,-4.397974,1.358367,-2.592844,2.679787,-1.128131,-1.706536,-3.496197,-0.248778,-0.247768,...,0.573574,0.176968,-0.436207,-0.053502,0.252405,-0.657488,-0.827136,0.849573,59.00,1
4,7519.0,1.234235,3.019740,-4.304597,4.732795,3.624201,-1.357746,1.713445,-0.496358,-1.282858,...,-0.379068,-0.704181,-0.656805,-1.632653,1.488901,0.566797,-0.010016,0.146793,1.00,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3378,78007.0,-2.768853,-3.520503,-0.509607,-1.941450,4.110432,1.855543,-0.812920,0.827134,-1.048479,...,0.145182,-0.495217,0.996258,0.831867,0.151155,0.268713,-0.272149,0.010948,317.90,0
3379,40229.0,-1.579246,1.919311,0.668699,1.605491,0.858920,-0.415322,1.266023,-0.513348,-0.986182,...,0.120527,0.174025,-0.281898,-0.115420,0.019312,-0.132365,-1.511504,-0.270925,7.20,0
3380,708.0,-0.560556,0.971554,1.777748,-0.317296,0.486242,-0.042579,0.970412,-0.253216,-0.283528,...,-0.275083,-0.278893,-0.079745,0.016083,-0.272718,0.029182,0.066240,-0.276698,9.87,0
3381,158616.0,-9.326717,-11.283392,1.401007,-0.023112,6.529104,-4.894877,-3.291586,0.380540,-0.209074,...,-0.038125,1.559860,6.667102,-0.448968,2.609676,0.165168,0.686945,-0.291362,10.00,0
3382,158140.0,-0.610063,0.623273,1.180651,-0.281960,-0.543633,-0.140922,-0.322534,0.687913,0.297171,...,0.388112,1.104578,-0.153749,0.017583,-0.530825,-0.217594,0.097164,0.109105,1.02,0

In [51]:
dados['Class'].value_counts(normalize=True)

Class
0    0.998273
1    0.001727
Name: proportion, dtype: float64

In [54]:
amostra_1['Class'].value_counts(normalize=True)

Class
0    0.854567
1    0.145433
Name: proportion, dtype: float64

---

 #### **Amostragem Polarizada por Densidade (BBS)**

O algoritmo BBS (Biased Box Sampling), é uma técnica de mineração de dados que seleciona elementos de forma que a probabilidade de inclusão dependa da densidade local da vizinhança. O objetivo é reduzir o volume de dados preservando a representatividade de agrupamentos (clusters) desbalanceados, pequenos ou raros, que seriam ignorados por uma amostragem uniforme. O BBS utiliza um mapeamento de multi-resolução do espaço de dados através de uma estrutura de árvore ($\text{MG-tree}$):
- Divisão do Espaço: O espaço é dividido recursivamente em $2^E$ regiões (onde $E$ é o número de atributos), dividindo cada atributo ao meio;
- Limiar de Divisão ($\delta$): Uma região só continua sendo dividida se o número de pontos for superior a $\delta$, definido como:
    - $\delta=\frac{2 \cdot E×100}{\text{Ratio}}​$, em que $\text{Ratio}$ é a taxa de amostragem desejada.
- Cálculo do Tamanho da Amostra (*samplesize*): Para cada nó folha na árvore compacta (MGc-tree), o número de pontos selecionados é ajustado pela sua profundidade para realizar um *oversampling* em regiões menos densas:
$$n = \left( \frac{Ratio \times C_{r,i}}{100} \right) \times 2 \times (R - \text{Nivel\_Atual})$$
em que:

- $C_{r,i}$​ é a contagem de pontos na célula, $R$ é o nível máximo e $\text{Nivel\_Atual}$ é o nível atual do nó. O custo total é linear: $O(N⋅E)$.

In [67]:
features = [col for col in dados.columns if col.startswith('V')]

from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
X_scaled = scaler.fit_transform(dados[features])
X_scaled = pd.DataFrame(X_scaled, columns=features)

In [69]:
grid_size = 5
X_disc = (X_scaled * grid_size).astype(int)

In [70]:
celulas = X_disc.groupby(list(X_disc.columns)).size()

In [71]:
densidade = X_disc.merge(
    celulas.rename("count"),
    left_on=list(X_disc.columns),
    right_index=True
)["count"]

In [72]:
peso = 1 / densidade

In [74]:
P = peso / peso.sum()

# Gera mais pontos do que precisa.
intermediate_size = int(len(dados) * 0.2)  # 20% (ajustável).

idx_inter = np.random.choice(len(dados),
                             size=intermediate_size,
                             replace=False,
                             p=P)

amostra_inter = dados.iloc[idx_inter]

In [76]:
final_size = 3383

idx_final = np.random.choice(len(amostra_inter),
                            size=final_size,
                            replace=False)

amostra_bbs = amostra_inter.iloc[idx_final]
amostra_bbs

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
224915,144022.0,1.631993,-0.695016,-1.708275,1.960974,0.211751,-0.228307,0.396074,-0.231889,-0.593353,...,0.368580,0.558042,-0.189117,0.617983,-0.129683,2.557531,-0.277336,-0.052910,239.47,0
70003,53667.0,1.130515,-1.433579,1.643958,-0.029566,-2.303826,0.400319,-1.666708,0.482628,0.837736,...,-0.484939,-0.684130,0.078956,0.553690,-0.005054,1.047140,-0.000103,0.015468,50.00,0
36855,38710.0,-6.891262,4.581844,-0.211804,-0.296554,-0.977211,1.470735,0.093121,0.280876,5.980607,...,-1.162030,-0.072345,-0.317393,-1.363652,1.797448,0.051850,2.129817,1.565045,25.00,0
116141,74160.0,-1.486108,1.060122,1.546694,-1.474047,-0.084776,-0.342548,0.631441,0.010829,0.859247,...,-0.150134,0.001684,0.035866,0.098991,-0.438594,0.733196,0.292959,0.184946,20.00,0
103846,68819.0,-2.311567,-1.288573,0.337324,-2.823147,-1.168683,0.596940,-0.612878,1.219470,-0.043679,...,0.004684,0.191373,0.082704,-0.614002,-0.625830,-0.130619,-0.055227,-0.218419,184.53,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95160,65190.0,-5.164795,4.510526,-0.994499,-1.110853,-0.913228,-0.889076,0.373572,0.361552,3.841062,...,-0.908623,-1.154210,0.300341,-0.102776,0.817800,0.201861,2.384092,1.576142,7.18,0
197620,132099.0,-0.595323,-0.650997,2.250973,-3.057740,-0.882374,0.297688,-0.717504,0.212475,-1.679692,...,-0.155164,-0.108392,-0.246277,0.444586,0.408334,-0.224512,0.063829,0.072073,26.00,0
186550,127154.0,-0.251898,-0.815926,-2.523551,-2.488000,1.019702,-1.709064,2.738913,-0.831904,0.907119,...,0.629087,1.614912,0.660527,0.608456,-0.825101,-0.233060,0.236254,0.191045,321.00,0
211629,138491.0,-1.263144,0.490776,0.982568,-1.305461,1.287332,2.058625,0.582804,-2.987205,1.983379,...,1.734588,-1.416266,0.596447,-0.722647,-1.371943,-0.428506,-0.959964,-0.926129,50.00,0
132473,79999.0,-5.245183,2.737862,0.202858,0.888079,0.091169,1.406935,-0.475813,-8.298159,2.286501,...,6.019600,-1.313162,0.845566,-0.011227,-0.297674,-0.452644,-3.302066,0.131687,31.52,0