## **4. Técnicas de Amostragem de Dados: Amostragem Por Cluster**

#### Autor: Tony Esaú de Oliveira
Universidade Federal do Cariri - UFCA

#### **O que é amostragem?**

O processo de amostragem é formalmente definido como a seleção de um subconjunto (denominado amostra) de membros de uma população ou conjunto de dados original, com o propósito de derivar estimativas e tirar conclusões sobre essa população utilizando apenas os membros selecionados. Matematicamente, se $N$ representa o número total de elementos na população e $n$ o tamanho da amostra $S$, o processo seleciona elementos de tal forma que $n<N$

#### **Característica Essencial de uma Amostragem:**

Para que a amostragem seja válida, a amostra deve ser **representativa**, o que significa que ela deve conservar as características e propriedades consideradas importantes do conjunto original. Assim, os resultados obtidos pela análise da amostra devem ser muito semelhantes aos que seriam encontrados caso toda a população fosse processada

#### **Importância**

A importância da amostragem reside na viabilização da análise de dados em larga escala através de diversos benefícios:

- **Redução do Volume e Custo Computacional**: A mineração de dados e a análise de grandes volumes são processos caros e complexos. A amostragem funciona como uma técnica de redução de dados que permite que algoritmos operem de forma mais eficiente e rápida, diminuindo a complexidade de tempo;

- **Economia de Recursos**: Em muitas aplicações, coletar dados de toda uma população é irrealista ou impossível devido aos altos custos financeiros, de tempo, materiais e de mão de obra. A amostragem permite obter informações confiáveis com gastos significativamente menores;

- **Agilidade e Tempestividade**: Por ser um processo mais rápido, a amostragem permite que os resultados sejam publicados e utilizados de forma oportuna. Em ciência de dados, uma resposta aproximada e rápida é frequentemente preferível a uma resposta exata que demore muito tempo para ser processada;

- **Melhoria na Qualidade dos Dados**: Como o volume de dados a ser tratado é menor, os investigadores podem ser mais cuidadosos na coleta, treinamento e supervisão, o que muitas vezes resulta em dados mais precisos do que os obtidos em um censo completo, que pode estar sujeito a erros administrativos e de coleta em larga escala;

- **Necessidade Técnica**: Em casos onde a medição exige a destruição da unidade de observação (como testes de laboratório), a amostragem é o único meio de obter informações sem eliminar toda a população.

---

## Students Performance

#### **Visão geral**

O dataset **Global University Students Performance & Habits** reúne informações sobre hábitos, estilo de vida e desempenho acadêmico de estudantes universitários ao redor do mundo. Seu objetivo é analisar como fatores comportamentais, sociais e tecnológicos influenciam o desempenho acadêmico.

#### **Estrutura dos dados**

* Total de instâncias: **10.000**
* Total de atributos: **27**

#### **Atributos**

O dataset contém variáveis **numéricas e categóricas**:

##### *Numéricas*

* `age`: idade do estudante;
* `GPA`: média geral (Grade Point Average);
* `study_hours_per_day`: horas de estudo por dia;
* `class_attendance_percent`: percentual de frequência;
* `sleep_hours`: horas de sono por dia;
* `screen_time_hours`: tempo de tela diário;
* `social_media_hours`: tempo em redes sociais;
* `gaming_hours`: tempo gasto com jogos;
* `exercise_hours_per_week`: horas de exercício por semana;
* `AI_tool_usage_hours`: uso de ferramentas de IA (horas);
* `exam_preparation_days`: dias de preparação para provas;
* `coffee_consumption_per_day`: consumo diário de café;
* `extracurricular_hours_per_week`: horas em atividades extracurriculares;
* `final_exam_score`: nota da prova final;
* `assignment_score`: nota de trabalhos.

##### *Categóricas*

* `student_id`: identificador do estudante;
* `gender`: gênero;
* `country`: país de origem;
* `major`: área de estudo;
* `university_year`: ano na universidade;
* `part_time_job`: indica se possui trabalho parcial;
* `relationship_status`: estado de relacionamento;
* `family_income_level`: nível de renda familiar;
* `internet_quality`: qualidade da internet;
* `mental_stress_level`: nível de estresse;
* `favorite_AI_tool`: ferramenta de IA favorita;
* `note_taking_method`: método de anotação;

#### **Variável alvo**

Dependendo do objetivo da análise, podem ser utilizadas:

* `GPA`
* `final_exam_score`
* `assignment_score`

#### **Observações importantes**

* Dataset rico em variáveis comportamentais e acadêmicas;
* Permite analisar a relação entre hábitos e desempenho;
* Inclui fatores modernos como uso de IA e tempo de tela;
* Combina variáveis numéricas e categóricas;
* Representa um cenário educacional **realista e multidimensional**.

---

In [5]:
import pandas as pd
import numpy as np

In [6]:
dados = pd.read_csv('Conjuntos_Dados/global_university_students_performance_habits.csv')

In [7]:
dados.head(10)

,student_id,age,gender,country,major,university_year,GPA,study_hours_per_day,class_attendance_percent,sleep_hours,...,internet_quality,mental_stress_level,AI_tool_usage_hours,favorite_AI_tool,note_taking_method,exam_preparation_days,coffee_consumption_per_day,extracurricular_hours_per_week,final_exam_score,assignment_score
0,S00001,23,Female,Germany,Law,4,3.81,4.2,96,6.2,...,Average,4.8,1.5,Claude,Digital,15,3,7.6,100,100
1,S00002,26,Female,USA,Economics,2,3.46,3.3,94,6.6,...,Average,3.9,2.3,Gemini,Mixed,11,3,5.2,100,83
2,S00003,18,Female,Canada,Medicine,3,4.00,4.5,100,6.3,...,Average,4.8,0.0,NaN,Mixed,12,3,4.6,100,100
3,S00004,20,Male,Australia,Physics,4,3.77,5.8,97,7.1,...,Good,5.9,2.9,Gemini,Mixed,11,1,4.0,100,98
4,S00005,28,Female,Australia,Medicine,2,4.00,3.1,96,8.4,...,Good,3.1,1.5,ChatGPT,Handwritten,15,4,1.4,100,94
5,S00006,18,Male,France,Medicine,2,4.00,3.1,96,6.1,...,Good,5.0,1.3,Claude,Digital,13,3,1.7,96,94
6,S00007,27,Male,Netherlands,Economics,1,4.00,5.9,100,8.2,...,Good,2.9,0.2,NaN,Handwritten,22,2,3.8,100,97
7,S00008,19,Male,Netherlands,Law,1,3.50,4.7,89,6.1,...,Good,5.0,0.6,Claude,Digital,10,0,0.0,100,93
8,S00009,20,Male,Japan,Biology,3,3.72,2.8,90,6.0,...,Average,5.3,0.8,Claude,Mixed,21,0,4.7,100,100
9,S00010,21,Female,Japan,Economics,2,3.47,4.3,100,8.0,...,Good,6.2,0.0,NaN,Handwritten,3,1,4.1,92,99

In [8]:
dados.shape

(10000, 27)

##### **Cálculo de Tamanho**

Para esse exemplo, iremos calcular o tamanho da amostra a partir do Intervalo de Confiança para Proporção:

$$\hat{p} \pm Z \cdot \sqrt{\frac{\hat{p}(1 - \hat{p})}{n}}$$

Em que:

- $\hat{p}$: Proporção observada na amostra (estimativa da proporção real).

- $Z$: Valor crítico da distribuição normal padrão (depende do nível de confiança).

- $n$: Tamanho da amostra.

- $\hat{p}(1 - \hat{p})$: Variância da proporção.

- $\sqrt{\frac{\hat{p}(1 - \hat{p})}{n}}$: Erro padrão da proporção (mede a variabilidade da estimativa).

Vamos calcular considerando $99\%$ de confiança e erro menor igual a $2\%$. Para isso devemos garantir que o erro padrão de proporção seja menor ou igual a $2\%$. Para isso, consideremos o pior caso para o denominador $\hat{p}(1-\hat{p})$, isto é, quando ele é maximizado. Um estudo quadrático simples, nos apontará que esse valor é $0,5$. Vamos rearranjar a fórmula sabendo disso:

$$Z \cdot \sqrt{\frac{\hat{p}(1 - \hat{p})}{n}} \leq 0,02$$
$$ \frac{1}{Z}Z \cdot \sqrt{\frac{\hat{p}(1 - \hat{p})}{n}} \leq \frac{1}{Z} 0,02$$
$$\sqrt{\frac{\hat{p}(1 - \hat{p})}{n}} \leq \frac{0,02}{Z}$$
$$\frac{\sqrt{(0,5)^2}}{\sqrt{n}} \leq \frac{0,02}{Z}$$
$$\frac{0,5}{\sqrt{n}} \leq \frac{0,02}{Z}$$
$$\frac{\sqrt{n}} {0,5} \geq \frac{Z}{0,02}$$
$$ \sqrt{n} \geq \frac{Z}{0,02} \cdot 0,5$$
$$ n \geq (\frac{Z}{0,04})^2$$

Calculando:

In [9]:
from scipy.stats import norm
import math

Z = norm.ppf(0.99)

n = math.ceil((Z/0.04)**2)
n

3383

Esse valor irá ser aproximado por cima o máximo possível.

 #### **Amostragem por Cluster (Agrupamento)**

A amostragem por agrupamento é uma técnica na qual a unidade de seleção é um grupo de elementos (cluster), e não os indivíduos isoladamente. Esses grupos são chamados de unidades primárias de amostragem ($\text{PSU}$).

Para realizar essa amostragem, consideremos uma população dividida em $N_c$ agrupamentos mutuamente exclusivos:

- **Estrutura**: cada agrupamento $i$ contém $M_i$ elementos. O total de elementos na população é:

$$N = \sum_{i=1}^{N_c}M_i$$

- **Seleção**: seleciona-se uma amostra aleatória simples de $n_c$ agrupamentos com $n_c < N_c$;
- **Processamento**: Todos os elementos pertencentes aos $n_c$ agrupamentos selecionados são incluídos na amostra final.
- **Probabilidade de Inclusão**: se todos os agrupamentos possuem o mesmo tamanho, a probabilidade de inclusão de qualquer elemento é:

$$P = \frac{n_c}{N_c}$$

##### **Cálculo do Número de Agrupamentos $N_c$**

O cálculo de $N_c$ depende de como iremos estruturar os agrupamentos. Cabe ressaltar que esses agrupamentos não devem ser **homogêneos** como o que ocorre numa amostragem estratificada, a característica de agrupamento deve utilizar um meio de forma que os membros dentro de um grupo tenham um nível de heterogeneidade. Por exemplo, poderíamos escolher bairros de uma cidade inteira, embora podemos agrupar, ainda existe alta heterogeneidade.

No nosso Conjunto de Dados de desempenho acadêmico iremos utilizar o país dos estudantes, esse agrupamento não implica em homogeneidade.

In [27]:
dados['country'].nunique()

13

Temos $13$ diferentes países. Logo, $N_c = 13$.

In [12]:
# Calculamos o tamanho médio dos clusters.
tamanho_medio_cluster = dados['country'].value_counts().mean()
tamanho_medio_cluster

np.float64(769.2307692307693)

##### **Cálculo do Número de Agrupamentos Escolhidos $n_c$**

Como fixamos um valor para o tamanho da amostra final devemos calcular o número de agrupamento escolhidos baseando-se na média dos tamanhos do agrupamentos. O que vai nos dar uma proximação de tamanho por cima do nosso tamanho fixado.

In [13]:
n_c = math.ceil(n / tamanho_medio_cluster)
n_c

5

Agora vamos escolher os agrupamentos.

In [20]:
# Escolha aleatória de n_c clusters.
clusters_selecionados = np.random.choice(dados['country'].unique(), size=n_c, replace=False)
clusters_selecionados

array(['Canada', 'Netherlands', 'Brazil', 'South Korea', 'UK'],
      dtype=object)

Selecionamos todos os elementos dos agrupamentos escolhidos.

In [22]:
amostra = dados[dados['country'].isin(clusters_selecionados)]
amostra

,student_id,age,gender,country,major,university_year,GPA,study_hours_per_day,class_attendance_percent,sleep_hours,...,internet_quality,mental_stress_level,AI_tool_usage_hours,favorite_AI_tool,note_taking_method,exam_preparation_days,coffee_consumption_per_day,extracurricular_hours_per_week,final_exam_score,assignment_score
2,S00003,18,Female,Canada,Medicine,3,4.00,4.5,100,6.3,...,Average,4.8,0.0,NaN,Mixed,12,3,4.6,100,100
6,S00007,27,Male,Netherlands,Economics,1,4.00,5.9,100,8.2,...,Good,2.9,0.2,NaN,Handwritten,22,2,3.8,100,97
7,S00008,19,Male,Netherlands,Law,1,3.50,4.7,89,6.1,...,Good,5.0,0.6,Claude,Digital,10,0,0.0,100,93
10,S00011,26,Female,Brazil,Biology,2,3.24,2.8,80,8.1,...,Good,4.3,0.9,Claude,Mixed,14,3,4.2,100,81
17,S00018,24,Male,Brazil,Law,4,4.00,4.0,100,7.5,...,Good,2.5,3.6,Copilot,Mixed,8,1,5.0,100,100
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9985,S09986,25,Female,Brazil,Biology,1,3.33,2.9,98,5.9,...,Good,4.9,0.7,ChatGPT,Digital,11,0,5.3,100,93
9986,S09987,26,Female,South Korea,Physics,4,3.54,2.9,96,5.7,...,Good,3.6,2.9,Copilot,Handwritten,4,3,0.8,100,97
9990,S09991,21,Female,Canada,Business,2,4.00,5.7,100,8.5,...,Average,3.3,1.5,Claude,Digital,12,2,6.4,100,96
9996,S09997,24,Male,Brazil,Psychology,4,2.90,0.5,75,8.7,...,Average,3.3,0.8,Copilot,Mixed,9,1,5.1,85,95
9998,S09999,23,Male,UK,Engineering,2,4.00,4.2,100,9.1,...,Average,1.0,1.2,Copilot,Mixed,13,4,2.6,97,97