## **2. Técnicas de Amostragem de Dados: Amostragem Sistemática**

#### Autor: Tony Esaú de Oliveira
Universidade Federal do Cariri - UFCA

#### **O que é amostragem?**

O processo de amostragem é formalmente definido como a seleção de um subconjunto (denominado amostra) de membros de uma população ou conjunto de dados original, com o propósito de derivar estimativas e tirar conclusões sobre essa população utilizando apenas os membros selecionados. Matematicamente, se $N$ representa o número total de elementos na população e $n$ o tamanho da amostra $S$, o processo seleciona elementos de tal forma que $n<N$

#### **Característica Essencial de uma Amostragem:**

Para que a amostragem seja válida, a amostra deve ser **representativa**, o que significa que ela deve conservar as características e propriedades consideradas importantes do conjunto original. Assim, os resultados obtidos pela análise da amostra devem ser muito semelhantes aos que seriam encontrados caso toda a população fosse processada

#### **Importância**

A importância da amostragem reside na viabilização da análise de dados em larga escala através de diversos benefícios:

- **Redução do Volume e Custo Computacional**: A mineração de dados e a análise de grandes volumes são processos caros e complexos. A amostragem funciona como uma técnica de redução de dados que permite que algoritmos operem de forma mais eficiente e rápida, diminuindo a complexidade de tempo;

- **Economia de Recursos**: Em muitas aplicações, coletar dados de toda uma população é irrealista ou impossível devido aos altos custos financeiros, de tempo, materiais e de mão de obra. A amostragem permite obter informações confiáveis com gastos significativamente menores;

- **Agilidade e Tempestividade**: Por ser um processo mais rápido, a amostragem permite que os resultados sejam publicados e utilizados de forma oportuna. Em ciência de dados, uma resposta aproximada e rápida é frequentemente preferível a uma resposta exata que demore muito tempo para ser processada;

- **Melhoria na Qualidade dos Dados**: Como o volume de dados a ser tratado é menor, os investigadores podem ser mais cuidadosos na coleta, treinamento e supervisão, o que muitas vezes resulta em dados mais precisos do que os obtidos em um censo completo, que pode estar sujeito a erros administrativos e de coleta em larga escala;

- **Necessidade Técnica**: Em casos onde a medição exige a destruição da unidade de observação (como testes de laboratório), a amostragem é o único meio de obter informações sem eliminar toda a população.

---

## Adult Census Income 

#### **Visão geral**

O dataset **Adult Census Income** é baseado em dados do censo dos Estados Unidos e tem como objetivo prever se a renda anual de uma pessoa excede **50 mil dólares**. É amplamente utilizado em aprendizado de máquina e análise estatística

#### **Estrutura dos dados**

* Total de instâncias: **32.561**
* Tarefa: **classificação binária**

#### **Atributos**

O dataset contém variáveis **categóricas e numéricas**:

##### *Numéricas*

`age`: idade;
* `fnlwgt`: peso amostral (importância da observação);
* `education-num`: nível de educação (numérico);
* `capital-gain`: ganhos de capital;
* `capital-loss`: perdas de capital;
* `hours-per-week`: horas trabalhadas por semana.

##### *Categóricas*

* `workclass`: tipo de emprego;
* `education`: nível de educação (texto);
* `marital-status`: estado civil;
* `occupation`: ocupação;
* `relationship`: relação familiar;
* `race`: raça;
* `sex`: gênero;
* `native-country`: país de origem;

#### **Variável alvo**

* `income`

  * `<=50K`
  * `>50K`

#### **Observações importantes**

* Alguns valores podem aparecer como `"?"` (dados faltantes simples);
* Mistura dados numéricos e categóricos;
* Representa um cenário **realista**, diferente de datasets artificiais.

---

In [65]:
import pandas as pd
import numpy as np

In [66]:
dados = pd.read_csv('Conjuntos_Dados/adult_census_income.csv')

In [67]:
dados.head(10)

,age,workclass,fnlwgt,education,education.num,marital.status,occupation,relationship,race,sex,capital.gain,capital.loss,hours.per.week,native.country,income
0,90,?,77053,HS-grad,9,Widowed,?,Not-in-family,White,Female,0,4356,40,United-States,<=50K
1,82,Private,132870,HS-grad,9,Widowed,Exec-managerial,Not-in-family,White,Female,0,4356,18,United-States,<=50K
2,66,?,186061,Some-college,10,Widowed,?,Unmarried,Black,Female,0,4356,40,United-States,<=50K
3,54,Private,140359,7th-8th,4,Divorced,Machine-op-inspct,Unmarried,White,Female,0,3900,40,United-States,<=50K
4,41,Private,264663,Some-college,10,Separated,Prof-specialty,Own-child,White,Female,0,3900,40,United-States,<=50K
5,34,Private,216864,HS-grad,9,Divorced,Other-service,Unmarried,White,Female,0,3770,45,United-States,<=50K
6,38,Private,150601,10th,6,Separated,Adm-clerical,Unmarried,White,Male,0,3770,40,United-States,<=50K
7,74,State-gov,88638,Doctorate,16,Never-married,Prof-specialty,Other-relative,White,Female,0,3683,20,United-States,>50K
8,68,Federal-gov,422013,HS-grad,9,Divorced,Prof-specialty,Not-in-family,White,Female,0,3683,40,United-States,<=50K
9,41,Private,70037,Some-college,10,Never-married,Craft-repair,Unmarried,White,Male,0,3004,60,?,>50K

In [68]:
dados.shape

(32561, 15)

In [69]:
dados[dados['income'] == '>50K'].shape[0]/dados.shape[0]

0.2408095574460244

In [70]:
dados[dados['income'] == '<=50K'].shape[0]/dados.shape[0]

0.7591904425539756

##### **Cálculo de tamanho**

Para esse exemplo, iremos calcular o tamanho da amostra a partir do Intervalo de Confiança para Proporção:

$$\hat{p} \pm Z \cdot \sqrt{\frac{\hat{p}(1 - \hat{p})}{n}}$$

Em que:

- $\hat{p}$: Proporção observada na amostra (estimativa da proporção real).

- $Z$: Valor crítico da distribuição normal padrão (depende do nível de confiança).

- $n$: Tamanho da amostra.

- $\hat{p}(1 - \hat{p})$: Variância da proporção.

- $\sqrt{\frac{\hat{p}(1 - \hat{p})}{n}}$: Erro padrão da proporção (mede a variabilidade da estimativa).

Vamos calcular considerando $99\%$ de confiança e erro menor igual a $2\%$. Para isso devemos garantir que o erro padrão de proporção seja menor ou igual a $2\%$. Para isso, consideremos o pior caso para o denominador $\hat{p}(1-\hat{p})$, isto é, quando ele é maximizado. Um estudo quadrático simples, nos apontará que esse valor é $0,5$. Vamos rearranjar a fórmula sabendo disso:

$$Z \cdot \sqrt{\frac{\hat{p}(1 - \hat{p})}{n}} \leq 0,02$$
$$ \frac{1}{Z}Z \cdot \sqrt{\frac{\hat{p}(1 - \hat{p})}{n}} \leq \frac{1}{Z} 0,02$$
$$\sqrt{\frac{\hat{p}(1 - \hat{p})}{n}} \leq \frac{0,02}{Z}$$
$$\frac{\sqrt{(0,5)^2}}{\sqrt{n}} \leq \frac{0,02}{Z}$$
$$\frac{0,5}{\sqrt{n}} \leq \frac{0,02}{Z}$$
$$\frac{\sqrt{n}} {0,5} \geq \frac{Z}{0,02}$$
$$ \sqrt{n} \geq \frac{Z}{0,02} \cdot 0,5$$
$$ n \geq (\frac{Z}{0,04})^2$$

Calculando:

In [71]:
from scipy.stats import norm
import math

Z = norm.ppf(0.99)

n = math.ceil((Z/0.04)**2)
n

3383

 #### **Amostragem Sistemática**

A Amostragem Sistemática é uma técnica que seleciona elementos de uma população a partir de um intervalo fixo, sendo frequentemente usada quando não existe uma lista com presença de padrões cíclicos e de preferência quando os dados da população estão em ordem completamente aleatória. Por outrolado, se a lista estiver ordenada por uma característica importante (ex: por data, geografia ou valor), o método funciona como uma "estratificação automática", garantindo que você capture elementos de todos os níveis de grandeza. Por exemplo, avaliar a qualidade de $20$ garrafas de vinho em uma esteira de produção ($N=20$) e precisa coletar $4$ garrafas ($n=4$) para teste.

Para realizar esse processo, seguimos estes passos:

- Definição do Intervalo ($k$): Determine o tamanho da população ($N$) e o tamanho da amostra desejada ($n$). O intervalo de amostragem é calculado como $k = \frac{N}{n}$ (arredondado para o inteiro mais próximo).
- Início Aleatório ($R$): Seleciona-se um número inteiro aleatório $R$, denominado "ponto de partida", tal que $1 \leq R \leq k$.
- Seleção da Amostra: A amostra será composta pelos elementos cujas posições na sequência são: $R,R+k,R+2k,…,R+(n−1)k$.

Se o intervalo $k$ possuir casas decimais, pode-se utilizar uma sequência de frações acumuladas para manter a precisão do tamanho da amostra final. Vamos realizar a composição dessa amostragem:

In [72]:
k = math.ceil(dados.shape[0]/n)
k

10

In [73]:
# Valor inicial R entre 0 e k-1.
import random

R = random.randint(0, k-1)
R

7

In [74]:
# A amostra é composta por elementos selecionados a cada k elementos, a partir do elemento R nas linhas tomando todas as colunas.
# Lembrando da sintaxe: dados.iloc[inicio:fim:passo, :] e : sozinho indica todos as colunas e .iloc toma os indices em detrimento das legendas.
amostra = dados.iloc[R-1::k, :]
amostra.head()

,age,workclass,fnlwgt,education,education.num,marital.status,occupation,relationship,race,sex,capital.gain,capital.loss,hours.per.week,native.country,income
6,38,Private,150601,10th,6,Separated,Adm-clerical,Unmarried,White,Male,0,3770,40,United-States,<=50K
16,45,Private,172822,11th,7,Divorced,Transport-moving,Not-in-family,White,Male,0,2824,76,United-States,>50K
26,33,Private,228696,1st-4th,2,Married-civ-spouse,Craft-repair,Not-in-family,White,Male,0,2603,32,Mexico,<=50K
36,53,Private,149650,HS-grad,9,Never-married,Sales,Not-in-family,White,Male,0,2559,48,United-States,>50K
46,71,Private,110380,HS-grad,9,Married-civ-spouse,Sales,Husband,White,Male,0,2467,52,United-States,<=50K

Vamos revisar a proporção da coluna `income`:

In [75]:
amostra[amostra['income'] == '>50K'].shape[0]/amostra.shape[0]

0.2367936117936118

In [76]:
amostra[amostra['income'] == '<=50K'].shape[0]/amostra.shape[0]

0.7632063882063882

Observe que em proporções, por conta da aleatoriedade, a representatividade é boa o suficiente.