### **11. Técnicas de Redução da Dimensionalidade: AutoEncoder** 

#### Autor: Tony Esaú de Oliveira.

##### Universidade Federal do Cariri

#### **Maldição da Dimensionalidade**

A maldição da dimensionalidade refere-se às severas dificuldades que surgem quando se trabalha com espaços que possuem muitas dimensões. À medida que a dimensionalidade ($D$) é aumentada, o número de regiões em uma grade regular cresce exponencialmente, tornando-se impraticável preencher esses espaços com dados suficientes para análises estatísticas. Geometricamente, as intuições desenvolvidas em três dimensões falham em espaços dimensionais superiores; por exemplo, em altas dimensões, a maior parte do volume de uma esfera concentra-se em uma casca fina perto de sua superfície e a massa de uma distribuição Gaussiana concentra-se em um anel fino a uma certa distância da origem.

#### **Redução de Dimensionalidade**

A redução de dimensionalidade é o processo de alterar a representação de dados complexos, originalmente descritos por um grande número de variáveis, para uma descrição de baixa dimensão usando apenas um pequeno número de parâmetros livres. Essa técnica pode ser implementada por meio de duas abordagens principais:

- **Seleção de atributos:** Identifica e seleciona o menor subconjunto de variáveis originais que melhor representam as características essenciais do problema, descartando as irrelevantes ou redundantes;
- **Extração de atributos:** Realiza transformações matemáticas ou combinações das variáveis originais para criar novas representações (como no método PCA), mantendo o máximo de informação possível em um número menor de dimensões.

A importância da redução de dimensionalidade reside em diversos fatores práticos e teóricos:

- **Eficiência Computacional e de Armazenamento:** Com a geração exponencial de dados (*Big Data*), a redução diminui a necessidade de espaço em disco e acelera drasticamente o tempo de processamento dos algoritmos;
- **Melhoria de Desempenho:** Ao eliminar redundâncias e ruídos ("informações irrelevantes"), as técnicas ajudam a evitar o sobreajuste (*overfitting*), permitindo que modelos de aprendizado de máquina alcancem maior precisão e generalização;
- **Visualização de Dados:** Projetar dados de alta dimensão em espaços de duas ou três dimensões permite que humanos visualizem estruturas, agrupamentos e padrões ocultos de forma intuitiva;
- **Estrutura Intrínseca:** Dados reais frequentemente residem em variedades não lineares (*manifolds*) de baixa dimensão embutidas no espaço de alta dimensão; a redução permite explorar essa estrutura efetiva inferior.

---

#### **Human Activity Recognition with Smartphones**

##### **Visão Geral**
- Classificação de atividades humanas (andar, sentar, etc.);
- ~3.000 amostras;
- 561 features;
- Dados de sensores de smartphone (acelerômetro e giroscópio).

##### **Origem dos Dados**
Sensores usados:
- Acelerômetro: movimento linear;
- Giroscópio: rotação.

Obs.: Celular posicionado na cintura dos usuários.

##### **Estrutura das Features**

Formato geral:

[t/f][Body/Gravity][Acc/Gyro]-[estatística]-[eixo]

##### **Componentes**

- **t / f**  
  - `t`: domínio do tempo;
  - `f`: domínio da frequência.

- **Tipo de sinal**  
  - `BodyAcc`: aceleração do corpo; 
  - `GravityAcc`: gravidade;
  - `BodyGyro`: rotação.

- **Estatísticas**  
  - `mean()`: média;
  - `std()`: desvio padrão; 
  - `energy()`: energia;
  - `entropy()`: entropia. 

- **Eixos**  
  - `X`, `Y`, `Z`


##### **Exemplo**

- `tBodyAcc-mean()-X`: média da aceleração no eixo X;  
- `fBodyGyro-energy()-Z`: energia do giroscópio no eixo Z.

##### Intuição

- Cada linha: um intervalo de movimento;
- Cada coluna: uma característica desse movimento.

---

#### **AutoEncoders**

Os AutoEncoders (também chamados de redes autoassociativas) são uma técnica de aprendizado não supervisionado baseada em redes neurais multicamadas, projetada para converter dados de alta dimensionalidade em representações compactas de baixa dimensão, chamadas de códigos. Formalmente, um autoencoder é definido como um modelo que busca aprender uma mapeamento autoassociativo, onde a rede é treinada para mapear vetores de entrada nela mesma. A arquitetura consiste em dois componentes fundamentais:

- Codificador (*Encoder*): Uma função (ou rede) que transforma os dados de alta dimensionalidade $x$ em um código latente $z$ de dimensão inferior;
- Decodificador (*Decoder*): Uma função que tenta recuperar ou reconstruir os dados originais $x$ a partir do código $z$.

O objetivo matemático é determinar os parâmetros (pesos e vieses) da rede minimizando uma função de erro de reconstrução, que captura a discrepância entre o vetor original e sua reconstrução. Frequentemente, utiliza-se a soma dos erros quadráticos para essa finalidade. Quando as camadas ocultas utilizam ativações lineares, o autoencoder é equivalente à Análise de Componentes Principais (PCA); no entanto, com camadas não lineares, ele atua como uma generalização não linear do PCA, capaz de revelar estruturas complexas nos dados.

A aplicação de Autoencoders para redução de dimensionalidade segue geralmente estes passos estruturais:

- **Definição da Arquitetura**: Projeta-se uma rede neural com um gargalo (camada latente de menor dimensão), forçando a compressão da informação;

- **Inicialização**: Em práticas modernas, utiliza-se inicialização padrão (ex: He ou Glorot). O pré-treinamento camada a camada (ex: RBMs) é historicamente relevante, mas raramente utilizado hoje devido à eficácia do treinamento direto com backpropagation;

- **Treinamento (Reconstrução)**: O modelo é treinado para minimizar o erro de reconstrução:
$$X \approx \hat{X}$$
usando *backpropagation* e otimizadores como Adam (Adaptive Moment Estimation);

- **Ajuste Fino (Fine-tuning)**: O treinamento já ocorre de forma conjunta em todas as camadas, não sendo necessário separar etapas como no pré-treinamento clássico;

- **Variante Variacional (VAE)**: Em contextos probabilísticos, o encoder aprende uma distribuição no espaço latente $(\mu, \sigma)$, e utiliza-se o truque da reparametrização. A função de perda combina:
    - Erro de reconstrução;
    - Divergência KL (regularização do espaço latente).

Uma vez treinado, o **encoder** é utilizado isoladamente para mapear dados de alta dimensão em um espaço latente reduzido.

---

#### Pipeline de Autoencoder (prático)

1. Pré-processamento:
   - Normalização (StandardScaler).

2. Definição da arquitetura:
   - Encoder (redução);
   - Decoder (reconstrução).

3. Compilação:
   - Perda: MSE (erro quadrático médio);
   - Otimizador: Adam.

4. Treinamento:
   - X -> X (entrada = saída)

5. Extração:
   - Usar apenas o encoder;

Pode ser usado para treinamento de modelo preditivo e de agrupamento, bem como para visualização em alguns casos.

---

In [1]:
import pandas as pd 
import numpy as np

In [2]:
dados = pd.read_csv('Conjunto_Dados/Human_Activity_Recognition_with_Smartphones.csv')

In [3]:
dados.head(10)

,tBodyAcc-mean()-X,tBodyAcc-mean()-Y,tBodyAcc-mean()-Z,tBodyAcc-std()-X,tBodyAcc-std()-Y,tBodyAcc-std()-Z,tBodyAcc-mad()-X,tBodyAcc-mad()-Y,tBodyAcc-mad()-Z,tBodyAcc-max()-X,...,fBodyBodyGyroJerkMag-kurtosis(),"angle(tBodyAccMean,gravity)","angle(tBodyAccJerkMean),gravityMean)","angle(tBodyGyroMean,gravityMean)","angle(tBodyGyroJerkMean,gravityMean)","angle(X,gravityMean)","angle(Y,gravityMean)","angle(Z,gravityMean)",subject,Activity
0,0.257178,-0.023285,-0.014654,-0.938404,-0.920091,-0.667683,-0.952501,-0.925249,-0.674302,-0.894088,...,-0.705974,0.006462,0.162920,-0.825886,0.271151,-0.720009,0.276801,-0.057978,2,STANDING
1,0.286027,-0.013163,-0.119083,-0.975415,-0.967458,-0.944958,-0.986799,-0.968401,-0.945823,-0.894088,...,-0.594944,-0.083495,0.017500,-0.434375,0.920593,-0.698091,0.281343,-0.083898,2,STANDING
2,0.275485,-0.026050,-0.118152,-0.993819,-0.969926,-0.962748,-0.994403,-0.970735,-0.963483,-0.939260,...,-0.640736,-0.034956,0.202302,0.064103,0.145068,-0.702771,0.280083,-0.079346,2,STANDING
3,0.270298,-0.032614,-0.117520,-0.994743,-0.973268,-0.967091,-0.995274,-0.974471,-0.968897,-0.938610,...,-0.736124,-0.017067,0.154438,0.340134,0.296407,-0.698954,0.284114,-0.077108,2,STANDING
4,0.274833,-0.027848,-0.129527,-0.993852,-0.967445,-0.978295,-0.994111,-0.965953,-0.977346,-0.938610,...,-0.846595,-0.002223,-0.040046,0.736715,-0.118545,-0.692245,0.290722,-0.073857,2,STANDING
5,0.279220,-0.018620,-0.113902,-0.994455,-0.970417,-0.965316,-0.994585,-0.969481,-0.965897,-0.937856,...,-0.857565,-0.095681,0.048849,0.760684,-0.072216,-0.689816,0.294896,-0.068471,2,STANDING
6,0.279746,-0.018271,-0.104000,-0.995819,-0.976354,-0.977725,-0.995996,-0.973665,-0.979253,-0.937856,...,-0.391286,-0.309083,-0.000857,0.728514,-0.333771,-0.690085,0.295282,-0.067065,2,STANDING
7,0.274601,-0.025035,-0.116831,-0.995594,-0.982069,-0.985262,-0.995341,-0.981485,-0.984610,-0.941263,...,-0.672358,-0.025526,-0.214033,0.437640,-0.366674,-0.688785,0.295981,-0.067706,2,STANDING
8,0.272529,-0.020954,-0.114472,-0.996784,-0.975906,-0.986597,-0.997029,-0.973735,-0.985556,-0.941263,...,-0.853248,0.144626,-0.035564,-0.181800,0.087320,-0.685390,0.299394,-0.065491,2,STANDING
9,0.275746,-0.010372,-0.099776,-0.998373,-0.986933,-0.991022,-0.998663,-0.987140,-0.991084,-0.943761,...,-0.741435,0.157584,-0.033487,-0.350893,0.343146,-0.684110,0.300822,-0.064263,2,STANDING

In [4]:
dados.shape

(2947, 563)

In [5]:
dados['Activity'].unique()

mapa = {
    'STANDING': 0,
    'SITTING': 1,
    'WALKING_DOWNSTAIRS': 2,
    'LAYING': 3,
    'WALKING': 4,
    'WALKING_UPSTAIRS': 5
}

dados['Activity'] = dados['Activity'].map(mapa)

---

### **AutoEncoder**

#### 1. Normalização

In [6]:
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

# Separar as features (X) e o alvo (y).
X = dados.drop('Activity', axis=1)
y = dados['Activity']

# Padronizar as features.
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Separar os dados em conjuntos de treino e teste, mantendo a proporção das classes.
X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y, test_size=0.2, random_state=42, stratify=y
)

#### 2. Construção do AutoEncoder

In [ ]:
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Dense

# Definir a dimensão de entrada e a dimensão de codificação (redução).
dimensao_entrada = X_train.shape[1]
dimensao_codificacao = 32  # Isso pode ser ajustado conforme necessário, é o gargalo da redução.

# Entrada: a mesma dimensão dos dados originais.
camada_entrada = Input(shape=(dimensao_entrada,))

# Codificador (Encoder): camadas densas que reduzem a dimensionalidade, com funções de ativação ReLU para introduzir não linearidade.
codificado = Dense(128, activation='relu')(camada_entrada) 
codificado = Dense(128, activation='relu')(camada_entrada) 
codificado = Dense(64, activation='relu')(codificado)
codificado = Dense(dimensao_codificacao, activation='relu')(codificado)

# Decodificador (Decoder): camadas densas que tentam reconstruir os dados originais a partir da representação 
# codificada, com função de ativação linear na última camada para permitir a reconstrução dos valores originais.
decodificado = Dense(64, activation='relu')(codificado)
decodificado = Dense(128, activation='relu')(decodificado)
decodificado = Dense(dimensao_entrada, activation='linear')(decodificado)

# Modelos: o autoencoder completo para treinamento e o codificador separado para obter as representações reduzidas.
autoencoder = Model(camada_entrada, decodificado)
codificador = Model(camada_entrada, codificado)

#### 3. Compilar

In [12]:
# Compilar o autoencoder: usamos o otimizador Adam, que é eficiente para muitos problemas de otimização, e a função de perda MSE (Mean Squared Error).
autoencoder.compile(
    optimizer='adam',
    loss='mse'
)

#### 4. Treinamento

In [49]:
# Treinar o autoencoder: o modelo é treinado para minimizar a diferença entre os dados de entrada e os dados reconstruídos, 
# usando um conjunto de validação para monitorar o desempenho durante o treinamento.

autoencoder.fit(
    X_train, X_train,
    epochs=50,
    batch_size=256,
    validation_split=0.2,
    verbose=1
)

Epoch 1/50
8/8 [==============================] - 0s 18ms/step - loss: 0.1079 - val_loss: 0.2054
Epoch 2/50
8/8 [==============================] - 0s 11ms/step - loss: 0.1080 - val_loss: 0.2055
Epoch 3/50
8/8 [==============================] - 0s 11ms/step - loss: 0.1079 - val_loss: 0.2046
Epoch 4/50
8/8 [==============================] - 0s 11ms/step - loss: 0.1081 - val_loss: 0.2058
Epoch 5/50
8/8 [==============================] - 0s 11ms/step - loss: 0.1082 - val_loss: 0.2050
Epoch 6/50
8/8 [==============================] - 0s 11ms/step - loss: 0.1084 - val_loss: 0.2059
Epoch 7/50
8/8 [==============================] - 0s 10ms/step - loss: 0.1086 - val_loss: 0.2057
Epoch 8/50
8/8 [==============================] - 0s 11ms/step - loss: 0.1086 - val_loss: 0.2043
Epoch 9/50
8/8 [==============================] - 0s 11ms/step - loss: 0.1082 - val_loss: 0.2048
Epoch 10/50
8/8 [==============================] - 0s 10ms/step - loss: 0.1080 - val_loss: 0.2049
Epoch 11/50
8/8 [==============================] - 0s 13ms/step - loss: 0.1088 - val_loss: 0.2056
Epoch 12/50
8/8 [==============================] - 0s 12ms/step - loss: 0.1082 - val_loss: 0.2051
Epoch 13/50
8/8 [==============================] - 0s 11ms/step - loss: 0.1081 - val_loss: 0.2056
Epoch 14/50
8/8 [==============================] - 0s 10ms/step - loss: 0.1083 - val_loss: 0.2055
Epoch 15/50
8/8 [==============================] - 0s 11ms/step - loss: 0.1083 - val_loss: 0.2051
Epoch 16/50
8/8 [==============================] - 0s 11ms/step - loss: 0.1077 - val_loss: 0.2052
Epoch 17/50
8/8 [==============================] - 0s 11ms/step - loss: 0.1076 - val_loss: 0.2047
Epoch 18/50
8/8 [==============================] - 0s 11ms/step - loss: 0.1078 - val_loss: 0.2056
Epoch 19/50
8/8 [==============================] - 0s 10ms/step - loss: 0.1080 - val_loss: 0.2048
Epoch 20/50
8/8 [==============================] - 0s 11ms/step - loss: 0.1079 - val_loss: 0.2050
Epoch 21/50
8/8 [==============================] - 0s 11ms/step - loss: 0.1081 - val_loss: 0.2057
Epoch 22/50
8/8 [==============================] - 0s 12ms/step - loss: 0.1081 - val_loss: 0.2054
Epoch 23/50
8/8 [==============================] - 0s 11ms/step - loss: 0.1078 - val_loss: 0.2055
Epoch 24/50
8/8 [==============================] - 0s 10ms/step - loss: 0.1079 - val_loss: 0.2052
Epoch 25/50
8/8 [==============================] - 0s 10ms/step - loss: 0.1077 - val_loss: 0.2056
Epoch 26/50
8/8 [==============================] - 0s 11ms/step - loss: 0.1077 - val_loss: 0.2063
Epoch 27/50
8/8 [==============================] - 0s 11ms/step - loss: 0.1078 - val_loss: 0.2056
Epoch 28/50
8/8 [==============================] - 0s 10ms/step - loss: 0.1078 - val_loss: 0.2061
Epoch 29/50
8/8 [==============================] - 0s 13ms/step - loss: 0.1079 - val_loss: 0.2055
Epoch 30/50
8/8 [==============================] - 0s 10ms/step - loss: 0.1076 - val_loss: 0.2052
Epoch 31/50
8/8 [==============================] - 0s 10ms/step - loss: 0.1075 - val_loss: 0.2053
Epoch 32/50
8/8 [==============================] - 0s 10ms/step - loss: 0.1075 - val_loss: 0.2051
Epoch 33/50
8/8 [==============================] - 0s 9ms/step - loss: 0.1074 - val_loss: 0.2052
Epoch 34/50
8/8 [==============================] - 0s 10ms/step - loss: 0.1073 - val_loss: 0.2055
Epoch 35/50
8/8 [==============================] - 0s 11ms/step - loss: 0.1075 - val_loss: 0.2055
Epoch 36/50
8/8 [==============================] - 0s 10ms/step - loss: 0.1077 - val_loss: 0.2056
Epoch 37/50
8/8 [==============================] - 0s 10ms/step - loss: 0.1077 - val_loss: 0.2061
Epoch 38/50
8/8 [==============================] - 0s 11ms/step - loss: 0.1078 - val_loss: 0.2054
Epoch 39/50
8/8 [==============================] - 0s 11ms/step - loss: 0.1076 - val_loss: 0.2057
Epoch 40/50
8/8 [==============================] - 0s 11ms/step - loss: 0.1075 - val_loss: 0.2056
Epoch 41/50
8/8 [==============================] - 0s 11ms/step - loss: 0.1074 - val_loss: 0.2053
Epoch 42/50
8/8 [==============================] - 0s 11ms/step - loss: 0.1073 - val_loss: 0.2052
Epoch 43/50
8/8 [==============================] - 0s 11ms/step - loss: 0.1075 - val_loss: 0.2056
Epoch 44/50
8/8 [==============================] - 0s 11ms/step - loss: 0.1076 - val_loss: 0.2049
Epoch 45/50
8/8 [==============================] - 0s 11ms/step - loss: 0.1076 - val_loss: 0.2053
Epoch 46/50
8/8 [==============================] - 0s 10ms/step - loss: 0.1075 - val_loss: 0.2057
Epoch 47/50
8/8 [==============================] - 0s 10ms/step - loss: 0.1076 - val_loss: 0.2059
Epoch 48/50
8/8 [==============================] - 0s 11ms/step - loss: 0.1075 - val_loss: 0.2058
Epoch 49/50
8/8 [==============================] - 0s 10ms/step - loss: 0.1076 - val_loss: 0.2058
Epoch 50/50
8/8 [==============================] - 0s 11ms/step - loss: 0.1075 - val_loss: 0.2054

#### 5. Redução de dimensionalidade

In [51]:
X_train_encoded = codificador.predict(X_train)
X_test_encoded = codificador.predict(X_test)

print(X_train.shape)        
print(X_train_encoded.shape)

74/74 [==============================] - 0s 2ms/step
19/19 [==============================] - 0s 2ms/step
(2357, 562)
(2357, 32)

In [54]:
dados_reduzidos = pd.DataFrame(X_train_encoded)
dados_reduzidos['Activity'] = y_train.values
dados_reduzidos.head(10)

,0,1,2,3,4,5,6,7,8,9,...,23,24,25,26,27,28,29,30,31,Activity
0,9.714965,0.0,0.000000,13.959688,0.000000,9.613257,10.971784,10.063408,5.131845,0.0,...,6.999751,0.0,0.000000,14.389984,0.000000,12.804625,3.482363,10.466169,11.478714,2
1,16.751753,0.0,0.000000,17.597210,0.000000,14.145611,19.882648,17.699884,3.347501,0.0,...,6.957239,0.0,0.000000,20.410227,0.000000,14.603310,6.972184,16.343172,14.218297,2
2,0.000000,0.0,6.623500,0.000000,8.229345,0.000000,5.468727,0.000000,7.277881,0.0,...,0.000000,0.0,4.534727,4.292251,5.278656,3.302975,8.285468,2.865994,4.160764,0
3,0.000000,0.0,5.753359,0.000000,10.048626,0.000000,4.459773,0.000000,1.338877,0.0,...,0.000000,0.0,7.636413,7.917604,5.955801,4.033328,5.399218,0.000000,3.392609,1
4,12.509805,0.0,0.000000,8.170373,0.000000,11.683900,9.866829,9.462056,9.268192,0.0,...,6.514846,0.0,0.000000,10.379744,0.000000,15.065343,3.764492,7.557040,20.963821,5
5,14.636027,0.0,0.000000,17.770414,0.000000,14.989059,15.752019,27.805834,8.437044,0.0,...,10.713331,0.0,0.000000,12.553534,0.000000,9.748803,0.000000,12.904381,7.791115,2
6,12.635473,0.0,0.000000,16.814674,0.000000,13.781403,17.739754,22.607737,4.489659,0.0,...,4.140248,0.0,0.000000,15.980231,0.000000,19.335114,5.632631,17.823957,8.774097,2
7,18.905771,0.0,0.000000,13.514687,0.000000,7.599602,16.653627,14.456558,10.359298,0.0,...,9.047456,0.0,0.000000,4.982674,0.000000,7.396509,10.074636,10.939769,12.480293,2
8,0.000000,0.0,5.864205,0.000000,15.307495,0.000000,8.963003,0.000000,4.681158,0.0,...,0.000000,0.0,7.549718,4.769506,7.119660,3.114960,10.134640,2.149613,3.164826,1
9,0.000000,0.0,9.286568,0.000000,11.285830,0.000000,4.391705,0.000000,6.105251,0.0,...,0.000000,0.0,4.646162,4.555923,6.051909,4.806254,11.201190,2.141463,5.494232,1

In [75]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

# =========================
# 1. MODELO NO ESPAÇO ORIGINAL
# =========================
clf1 = RandomForestClassifier(n_estimators=100, random_state=42)

clf1.fit(X_train, y_train)
y_pred1 = clf1.predict(X_test)

acc_original = accuracy_score(y_test, y_pred1)


# =========================
# 2. MODELO NO ESPAÇO COMPRIMIDO
# =========================
clf2 = RandomForestClassifier(n_estimators=100, random_state=42)

clf2.fit(X_train_encoded, y_train)
y_pred2 = clf2.predict(X_test_encoded)

acc_encoded = accuracy_score(y_test, y_pred2)


# =========================
# 3. RESULTADOS
# =========================
print("Accuracy original:", acc_original)
print("Accuracy encoded:", acc_encoded)

Accuracy original: 0.988135593220339
Accuracy encoded: 0.9271186440677966