In [3]:
import pandas as pd

df = pd.read_parquet("hf://datasets/to-be/epstein-emails/emails.parquet")

In [3]:
df.shape

(4272, 12)

In [4]:
df.columns

Index(['id', 'email_document_id', 'source_filename', 'subject',
       'message_order', 'from_address', 'to_address', 'other_recipients',
       'timestamp_raw', 'timestamp_iso', 'message_html', 'document_id'],
      dtype='object')

Converter coluna 'from_address' e 'to_address' para strings, caso já não sejam.

In [5]:
df['from_address'] = df['from_address'].fillna('').astype(str) # NAN caso vazio
df['to_address']   = df['to_address'].fillna('').astype(str)

In [6]:
df[['from_address', 'to_address']].isna().sum()

from_address    0
to_address      0
dtype: int64

Converter 'other_recipients' para um vetor do tipo [obj_1, obj_2, ..., obj_n].

In [8]:
import ast

df['other_recipients'] = (
    df['other_recipients']
    .fillna('[]')
    .apply(lambda x: ast.literal_eval(x) if isinstance(x, str) else x)
)

Agora vamos expandir 'other_recipients' em linhas copiadas individuais e também 'to_address' caso exista endereços múltiplos.

Agora fazemos a expansão.

In [9]:
import re

# 1) Garante que other_recipients é lista
df['other_recipients'] = df['other_recipients'].apply(lambda x: x if isinstance(x, list) else [])

# 2) Converte to_address em lista quando tiver múltiplos
def split_to_address(x):
    if not isinstance(x, str):
        return []
    partes = re.split(r'[;,]', x)
    return [p.strip() for p in partes if p.strip()]

df['to_address_list'] = df['to_address'].apply(split_to_address)

# 3) Junta to_address + other_recipients num único vetor
df['todos_destinatarios'] = df.apply(
    lambda row: row['to_address_list'] + row['other_recipients'],
    axis=1
)

# 4) Explode tudo em linhas individuais
df_exp = df.copy()
df_exp['destinatario'] = df_exp['todos_destinatarios']
df_exp = df_exp.explode('destinatario')

# 5) Substitui to_address e limpa other_recipients
df_exp['to_address'] = df_exp['destinatario']
df_exp['other_recipients'] = [[] for _ in range(len(df_exp))]

# 6) Remove colunas auxiliares
df_final = df_exp.drop(columns=['to_address_list', 'todos_destinatarios', 'destinatario'])

In [14]:
df_final.shape

(5022, 12)

In [13]:
df_final['other_recipients'].apply(len).eq(0).sum()

np.int64(5022)

In [15]:
df_final.head()

,id,email_document_id,source_filename,subject,message_order,from_address,to_address,other_recipients,timestamp_raw,timestamp_iso,message_html,document_id
0,1,1,HOUSE_OVERSIGHT_012102.txt,Email subject of the thread,0,Jeffrey Epstein,Nicholas Ribis,[],5/7/2019 4:29:00 AM,20190507042900,<a href='https://www.nytimes.com/2019/05/06/us...,HOUSE_OVERSIGHT_012102
1,2,2,HOUSE_OVERSIGHT_012898.txt,Farmer Jaffe is suing Donald Trump!,0,Tonja Haddad Coleman,Jeffrey Epstein,[],5/13/2013 10:28:30 PM,20130513222830,Farmer Jaffe is suing Donald Trump!<br><a href...,HOUSE_OVERSIGHT_012898
1,2,2,HOUSE_OVERSIGHT_012898.txt,Farmer Jaffe is suing Donald Trump!,0,Tonja Haddad Coleman,Darren Indyke,[],5/13/2013 10:28:30 PM,20130513222830,Farmer Jaffe is suing Donald Trump!<br><a href...,HOUSE_OVERSIGHT_012898
1,2,2,HOUSE_OVERSIGHT_012898.txt,Farmer Jaffe is suing Donald Trump!,0,Tonja Haddad Coleman,Debbie Fein,[],5/13/2013 10:28:30 PM,20130513222830,Farmer Jaffe is suing Donald Trump!<br><a href...,HOUSE_OVERSIGHT_012898
2,3,3,HOUSE_OVERSIGHT_014516.txt,Fwd: 2016 Election: Tax Changes Expected,0,Richard Kahn,Jeffrey Epstein,[],12/15/2016 5:40:04 PM,20161215174004,,HOUSE_OVERSIGHT_014516

Vamos apagar as duplicatas:

In [16]:
df_final = df_final.drop_duplicates(
    subset=[
        'id', 'email_document_id', 'source_filename', 'subject',
        'message_order', 'from_address', 'to_address',
        'timestamp_raw', 'timestamp_iso', 'message_html', 'document_id'
    ],
    keep='first'
)

Criando csv com três colunas: 'de', 'para' e 'assunto'.

In [17]:
def criar_csv_de_para_assunto(df_final):
    df_saida = df_final[['from_address', 'to_address', 'subject']].copy()
    df_saida.columns = ['de', 'para', 'assunto']
    return df_saida

df_saida = criar_csv_de_para_assunto(df_final)

In [18]:
df_saida.head(15)

,de,para,assunto
0,Jeffrey Epstein,Nicholas Ribis,Email subject of the thread
1,Tonja Haddad Coleman,Jeffrey Epstein,Farmer Jaffe is suing Donald Trump!
1,Tonja Haddad Coleman,Darren Indyke,Farmer Jaffe is suing Donald Trump!
1,Tonja Haddad Coleman,Debbie Fein,Farmer Jaffe is suing Donald Trump!
2,Richard Kahn,Jeffrey Epstein,Fwd: 2016 Election: Tax Changes Expected
3,"Ens, Amanda",Richard Kahn,Fwd: 2016 Election: Tax Changes Expected
4,Nicholas Ribis,Jeffrey Epstein,RE:
5,John Page,Mayor,Russian House
6,<REDACTED>,John Page,Russian House
7,"Ens, Amanda",Jeffrey Epstein,SPX put contingent on higher rates
7,"Ens, Amanda",Richard Kahn,SPX put contingent on higher rates
8,<REDACTED>,John Page,Trump house
9,John Page,Mayor,Trump house
10,"Ens, Amanda",Jeffrey Epstein,Meet with our Global Head of Commodities - Mon...
10,"Ens, Amanda",Richard Kahn,Meet with our Global Head of Commodities - Mon...

Agora vamos ver os valores únicos e dropar os valores inúteis.

In [21]:
def limpar_nome(x):
    if not isinstance(x, str):
        return x
    
    # Remove emails entre < >.
    x = re.sub(r'<[^>]+>', '', x)
    
    # Remove emails soltos.
    x = re.sub(r'\b[\w\.-]+@[\w\.-]+\.\w+\b', '', x)
    
    # Remove aspas, colchetes, parênteses.
    x = re.sub(r'["\[\]\(\)]', '', x)
    
    # Remove múltiplos espaços.
    x = re.sub(r'\s+', ' ', x).strip()
    
    return x

Aplicando:

In [22]:
df_saida['de'] = df_saida['de'].apply(limpar_nome)
df_saida['para'] = df_saida['para'].apply(limpar_nome)

Vamos remover linhas que ficaram com 'de' ou 'para' vazios.

In [23]:
df_saida = df_saida[
    df_saida['de'].notna() & df_saida['para'].notna() &
    (df_saida['de'].str.strip() != '') &
    (df_saida['para'].str.strip() != '')
]

In [24]:
print("Linhas restantes:", len(df_saida))

Linhas restantes: 4825

Agora vamos atacar os valores únicos, pois provavelmente tem valores que se referem as mesmas pessoas sendo vistas de maneira distintas.

In [25]:
pessoas_de = df_saida['de'].unique()
pessoas_de = sorted(pessoas_de)
for pessoa in pessoas_de:
    print(pessoa)

-11>
-1M1=1111M1>
111
1=1=11111M11
<1111111
<1=1=11111M11
<>
>
????
A Barrett
Afri zp
Al Franken
Al seckel
Al seckel 111111111111111.11111111111111111
Alan
Alan Dershowitz
Alan Rogers
Alexandra Preate
Alireza ITTIHADIEH
Alireza Ittihadieh
Anas Alrasheed
Anders Corr
Andres Serrano
Andrew Friendly
Anil Ambani
Anil.Ambani
Ann Coulter
Annette Witheridge
Ariane de Rothschild
Ashley Parker
Auren Hoffman
BARBRO EHNBOM
BRYAN SUBOTNICK
BRYAN SUBOTNICK 411111111111>
Barbro C Ehnbom
Barbro C. Ehnbom
Barbro Ehnbom
Barnaby Marsh
Barry J. Cohen
Barry J. Cohen <>
Barry Josephson
Benjamin Harnwell
Benjamin Harnwell <
Benjamin Harnwell <>
Benjamin Wegg-Prosser
Bill Siegel
Blanche Christerso
Bloomberg
Bob Crowe
Boris Nikoli
Boris Nikolic
Brad Edwards
Brad Wechsler <>
Brandon Thompson
Browning, Jack mailto
Bruce Moskowitz
CLL
CNS Adam Klasfeld
Carolyn Rangel
Cathy Alexander
Cecilia Schott
Cecilia Schött
Cecilia Steen
Christina Galbraith
Comms Alert
DAN CHRISTENSEN
DAVID SCHOEN
Dangene and Jennie Enterprise
Daniel Sabba
Daniel Sabba I
Daniel Siad
Darren Indyke
Darren Indyke <________________
Darren K. Indyke
Darren lndyke
Dave Hope
David
David Bianco, Deutsche Bank
David Blaine
David Fiszel
David Grosof
David I. Schoen
David Mitchell
David Pegg
David Schoen
David Schoen <>
David Stern
David Willis
Deepak Chopra
Deepak Chopra <>
Deepak Chopra <__________________________
Deepak Chopra____________
Diane Ziman
Diane Ziman <>
Dick Cavett
Donald Rubin
Donald Trump
Dr. Bruce L. Dennis <>
EL HACHEM Johnny
Ed
Ed Boyden
Ed Boyden <>
Ed Boyden <______________________
Edward Epstein
Edward Rod Larsen
Edyta.Wynberg
Ehud Barak
Eisenberg, Marshall E.
Elisa New
Ens, Amand
Ens, Amanda
Eric Roth
Eric Roth <>
Erika Kellerhals
Esneh
Etienne Binant
Eva pichand
FT Breaking News
Fabrice Aidan
Faith Kate
Faith Kates
Faith Kates <>
Fareed Zakaria GPS
Florence Anthony
Fred Beck
Fred Haddad
Fred Haddad <>
G Maxwell
GBIU-MideastNews
GMAX
Gerald Barton
Ghislaine Maxwell
Gi Feather on behalf of Gerald Barton
Gianni Serazzi
Gino Yu
Gmax
Gonzalez, Patricia
Google Alerts
Gordon Getty
Greg
Greg Farrell BLOOMBERG/ NEWSROOM:
Guy Amico
Guy Amico <>
Gwendolyn
HOUSE OVERSIGHT
HOUSE OVERSIGHT 026675
HOUSE OVERSIGHT 032374
HOUSE OVERSIGHT 032605
HOUSE OVERSIGHT 033178
HOUSE OVERSIGHT 033246
HOUSE OVERSIGHT 033292
HOUSE OVERSIGHT 033309
HOUSE_OVERSIGHT_029969
HOUSE_OVERSIGHT_030630
HOUSE_OVERSIGHT_030807
HOUSE_OVERSIGHT_030874
Haig, David
Harry Fisch
Hayes, David L., M.D.
Heather Man
Heather Mann
Heberlig, Brian
Hill, James E.
Hope, Doug
How To Academy
Howard Rubenstein
Howard Rubenstein <>
IMMIIIIIMIMI
I_____________________________
Ian Osborne
Immelt, Stephen J.
Ingram, David Reuters News
Investigative Reporter, FoxNews.com
J
J Jep
JEE
JONATHAN FARKAS
JONATHAN FARKASIIII
Jabor Y
Jabor Y.
Jabor Y. INEWEI
Jack Goldberger
Jack LANG
Jack LANG <>
Jacquie Johnson
Jakob Kollhofer
James Drougas
Jamie Rosenwald
Jamie Rosenwald <___________________________________
Jason Miller
Jay Lefkowitz
Jean HUGUEN
Jean Luc Brunel
Jeffrey Epstein
Jennifer Jacquet
Jeremy Rubin
Jesse Kornbluth
Jessica Cadwell
Jessica Cadwell, Paralegal
Jide Zeitlin
Joel
Joel Dunn
John Brockman
John Connolly Ed.D.
John Page
Joi Ita
Joi Ito
Joi Ito <
Joi Ito <>
Joichi Ito
Jonathan
Jonathan Farkailll
Jonathan Farkas
Jonathan Farkas ..111.
Joscha Bach
Joshua Cooper Ramo
Justin Blackhall
Kaczorowski, Monice M.
Karp, Brad S
Kate Briquelet
Katherine Keating
Kathy
Kathy Ruemmle
Kathy Ruemmler
Kathy Ruemmler <
Kathy Ruemmler <____________________
Kathy Ruemmler <_______________________
Kathy Ruemmler <____________________________-
Kathy Ruemmler___________________
Kathy Ruemmlerl
Katily Ruemmler imumniummu
Kelly Friendly
Kelly Friendly <>
Ken Star
Ken Starr
Ken Starr <
Ken Starr <>
Ken Starr <__________________
Ken Starr__________________________________
Kevin Frost
Keyu Jin
Kirsty Mackenzie
Kristin Andersen
LH
LHS
LHS <
LHS <>
LHS___________
LHS__________________________
Landon Thomas
Landon Thomas Jr.
Landon Thomas Jr. <
Lang, Caroline
Larry
Larry Summer
Larry Summers
Larry Summers -
Larry Summers <
Larry Summers <>
Larry Visosk
Larry Visoski
Larry Visoski <>
Laurie Cameron
Lawrance Visoski
Lawrence H. Summers
Lawrence H. Summers <>
Lawrence Krauss
Lawrence Krauss <>
Lawrence Summers
Lawrence Summers <>
Lawrence Visoski
Leah Reis-Dennis
Leah Reis-Dennis <1
Leon Black
Leon Black <IMMIMI
Lesley Groff
Lesley Groff <>
Lesley Groff I_____________________________
Lilly Sanchez
Lilly Sanchez <___________________
Lilly Sanchez I
Linda Pinto
Linda Stone
Linda Stone <I_______________________r-
Lisa Ne
Lisa New
Lisa New <1
Lisa New <>
Lisa New________________________
Lisa Rossi
Lonnie Martin
Lvje
Lvjet
MARK TRAMO
MMIIIMIM
MOMMINNEMUMMIN
Magdalena Schuster
Manuela Wieland
Marc.Kensington
Margaret Slattery
Maria Luisa
Maria T. Zuber
Mark Cohen
Mark Green
Mark L. Epstein
Mark Lloyd
Martin G. Weinberg <
Martin G. Weinberg <>
Martin Weinberg
Martin Weinberg iMiniMIM>
Masha Drokova
Masha Drokova <________________
Maskin, Eric
Matt Williams
Matthew Hiltzik
Matthew Mosk
Melanie Hicken
Melanie Spinella
Melanie Walker
Merwin Dela cruz
Michael Braun
Michael Greenberg
Michael Reiter/PalmBeach
Michael Wolff
Michael Wolff -
Michael Wolff 111111111111111.1111111111.1.1.11111111111111.
Michael Wolff <1.111'
Michael Wolff <1111
Michael Wolff <>
Michael Wolff <________________
Michael Wolff <j____________________________k
Michael Wolff MMMNIMMIMMI
Michael Wolff _______________________________
Michael Wolff______________________
Michael Wolffl
Michael, Charles
Mike Cohen
Miles Alexander
Miller, Micha
Miller, Michael
Miroslav Lajčák
Mohamed Waheed
Mohamed Waheed Hassan
Mohammed Waheed Hassan
Morgan Stanley
Moshe Hoffman
Mosk, Matthew
Moskowitz, Bennet J.
NYTimes.com News Alert
Nadia
Nay Gupta
Neal Kassel
Neal Kassell
Neil Gershenfeld
Neil Gershenfeld <>
Newsmax. corn
Niall McCarthy | Statista
Nicholas Drinkwater
Nicholas Ribis
Noam Chomsky
Nowak, Martin A.
Ozan Tarman
Ozan Tarman <_____________________
PETER MANDELSON
PLI
Palazzolo, Joseph
Parker, Ashley
Parker, Ashley <>
Paul Barred
Paul Barrett
Paul Krassner
Paul Morris
Paul Prosperi
Paul Schulte
Paula
Peggy
Peggy Siegal
Peggy Siegal <>
Peggy SiegalliM1111.1.1
Peter Atti
Peter Attia
Peter Mandelson
Peter Mandelson <________________________________
Peter Thiel
Philip Barden
Philip Levine
Pickier, Nedra
Pizzurro, Frank LA
Prateek Jain
Prince Bandar bin Sultan
Pritzker, Tom
Purevsuren Lundeg
Ramsey Elkholy
Raw Story Overnight
Rebecca Watson
Reid Hoffman
Reid Weingarten
Renata B
Renata Bolotova
Richard John Nawrot
Richard Kahn
Richard Kahn <>
Richard Kahn___________________________
Richard Merkin
Robert D. Critton Jr.
Robert Grusky
Robert Grusky <>
Robert Kuhn
Robert Kuhn •
Robert L. Kuhn
Robert Lawrence Kuhn
Robert Trivers
Robert Trivers <>
Robert Triversi
Ross Gow
Roy Black
Ruberto Israel & Weiner
Rush, George
Rush, George mailto
Scoop Notifications
Scott J. Lin
Scott J. Link
Sean Banno
Sean Bannon
Sean J. Lancaster
Shaher
Shanson900
Sharon Churcher
Sharon Churcher <>
Sheikh
Sidney Blumenthal
Skip Rimer
SmartBrief on Business & Politics
Soon-Yi
Stanley Rosenberg
Starr, Ken
Stephanie
Stephen Alexander
Stephen Hanso
Stephen Hanson
Steve Bannon
Steve Bannon <
Steve Bannon <>
Steve Bannon <__________________
Steve Bannon <____________________
Steve Bannor
Steve Hanson
Steve Hanson <>
Steven Elkman
Steven Elkman <>
Steven Pfeiffer
Steven Pfeiffer <_
Steven Pfeiffer <_________________
Steven Sinofsky
Stevenhoffenberg
Stewart Oldfield
Sullivan, John
Sultan Bin Sulayem
Tamem
Tanzi, Rudolph E
Terje Rod-Larsen
Terry Kafka
Tesley Groff
The Daily Beast: PM Cheat Sheet
The Washington Post
Thomas D. Williams
Thomas Jr., Landon
Thomas Jr., Landon <>
Thomas Jr., Landon <_______________________
Thomas Jr., Landon <________________________
Thomas Jr., Landor
Thomas L. Friedman
Thorbjon JagIan
Thorbjon Jagland
Thorbjon Jagland <>
Thorbjørn Jagland
Tim Zagat
Timothy Jones
Tom Barrack Private
Tonja Haddad Coleman
Tonja Haddad Coleman <>
Tyler Shears
Valeria Chomsky
Vincenzo lozzo
Vinit Sahni
Vinoda Basnayake
Weingarten, Reid
William L. Blum
William McLendon
Wolfe, Alexandra
Zimmerman, Malia McLaughlin
Zubair Khan
abuulabass
admin
anasalrasheed
anasalrasheed1111
anasalrasheed______________
anil.ambani
aziza alahmadi
drsra
ed thompson
ehbarak
elisabeth feliho
gmax
habebey
lawkrauss
live:linkspirit
martin Weinberg
nk.mb
paul krassner
ro
sender name or email
soon yi previn
soon yi previn_________________________
stanpottinger
stanpottinger mailto
steven hoffenberg
tamem
thnx jeff i m praying44

Aplicando mapeamento para limpeza e padronização da coluna 'de'.

In [27]:
mapeamento = {
    "-11>": "Desconhecido 1",
    "-1M1=1111M1>": "Desconhecido 2",
    "111": "Desconhecido 3",
    "1=1=11111M11": "Desconhecido 4",
    "<1111111": "Desconhecido 5",
    "<1=1=11111M11": "Desconhecido 6",
    "<>": "Desconhecido 7",
    ">": "Desconhecido 8",
    "????": "Desconhecido 9",
    "Al seckel 111111111111111.11111111111111111": "Al seckel",
    "Alan": "Alan Dershowitz",
    "Alireza ITTIHADIEH": "Alireza Ittihadieh",
    "Anil.Ambani": "Anil Ambani",
    "anil.ambani": "Anil Ambani",
    "BARBRO EHNBOM": "Barbro C. Ehnbom",
    "Barbro C Ehnbom": "Barbro C. Ehnbom",
    "Barbro Ehnbom": "Barbro C. Ehnbom",
    "BRYAN SUBOTNICK": "Bryan Subotnick",
    "BRYAN SUBOTNICK 411111111111>": "Bryan Subotnick",
    "Barry J. Cohen <>": "Barry J. Cohen",
    "Barry Josephson": "Barry J. Cohen",
    "Benjamin Harnwell <": "Benjamin Harnwell",
    "Benjamin Harnwell <>": "Benjamin Harnwell",
    "Boris Nikoli": "Boris Nikolic",
    "Brad Wechsler <>": "Brad Wechsler",
    "Browning, Jack mailto": "Jack Browning",
    "Cecilia Schott": "Cecilia Schött",
    "DAN CHRISTENSEN": "Dan Christensen",
    "DAVID SCHOEN": "David Schoen",
    "Daniel Sabba I": "Daniel Sabba",
    "Darren Indyke <________________": "Darren K. Indyke",
    "Darren Indyke": "Darren K. Indyke",
    "David": "David Bianco, Deutsche Bank",
    "David Schoen <>": "David Schoen",
    "Deepak Chopra <>": "Deepak Chopra",
    "Deepak Chopra <__________________________": "Deepak Chopra",
    "Deepak Chopra____________": "Deepak Chopra",
    "Diane Ziman <>": "Diane Ziman",
    "Dr. Bruce L. Dennis <>": "Dr. Bruce L. Dennis",
    "EL HACHEM Johnny": "Johnny el Hachem",
    "Ed Boyden <>": "Ed Boyden",
    "Ed Boyden <______________________": "Ed Boyden",
    "Ed": "Ed Boyden",
    "Edyta.Wynberg": "Edyta Wynberg",
    "Eisenberg, Marshall E.": "Marshall E. Eisenberg",
    "Ens, Amand": "Amanda Ens",
    "Ens, Amanda": "Amanda Ens",
    "Eric Roth <>": "Eric Roth",
    "Eva pichand": "Eva Pichand",
    "Faith Kates <>": "Faith Kates",
    "Faith Kate": "Faith Kates",
    "Fareed Zakaria GPS": "Fareed Zakaria",
    "Fred Haddad <>": "Fred Haddad",
    "G Maxwell": "Ghislaine Maxwell",
    "GMAX": "Ghislaine Maxwell",
    "Gmax": "Ghislaine Maxwell",
    "gmax": "Ghislaine Maxwell",
    "Gi Feather on behalf of Gerald Barton": "Gerald Barton",
    "Gonzalez, Patricia": "Patricia Gonzalez",
    "Greg": "Greg Farrell",
    "Greg Farrell BLOOMBERG/ NEWSROOM:": "Greg Farrell",
    "Guy Amico <>": "Guy Amico",
    "Gwendolyn": "Gwendolyn Beck",
    "HOUSE OVERSIGHT": "House Oversight",
    "HOUSE OVERSIGHT 026675": "House Oversight",
    "HOUSE OVERSIGHT 032374": "House Oversight",
    "HOUSE OVERSIGHT 032605": "House Oversight",
    "HOUSE OVERSIGHT 033178": "House Oversight",
    "HOUSE OVERSIGHT 033246": "House Oversight",
    "HOUSE OVERSIGHT 033292": "House Oversight",
    "HOUSE OVERSIGHT 033309": "House Oversight",
    "HOUSE_OVERSIGHT_029969": "House Oversight",
    "HOUSE_OVERSIGHT_030630": "House Oversight",
    "HOUSE_OVERSIGHT_030807": "House Oversight",
    "HOUSE_OVERSIGHT_030874": "House Oversight",
    "Haig, David": "David Haig",
    "Hayes, David L., M.D.": "Dr. David L. Hayes",
    "Heather Mann": "Heather Man",
    "Heberlig, Brian": "Brian Heberlig",
    "Hill, James E.": "James E. Hill",
    "Hope, Doug": "Doug Hope",
    "Howard Rubenstein <>": "Howard Rubenstein",
    "IMMIIIIIMIMI": "Desconhecido 10",
    "I_____________________________": "Desconhecido 11",
    "Immelt, Stephen J.": "Stephen J. Immelt",
    "Ingram, David Reuters News": "David Ingram News",
    "J": "Desconhecido 12",
    "J Jep": "Desconhecido 12",
    "JEE": "Desconhecido 12",
    "JONATHAN FARKAS": "Jonathan Farkas",
    "JONATHAN FARKASIIII": "Jonathan Farkas",
    "Jonathan": "Jonathan Farkas",
    "Jonathan Farkailll": "Jonathan Farkas",
    "Jonathan Farkas ..111.": "Jonathan Farkas",
    "Jabor Y. INEWEI": "Jabor Y. Inewey",
    "Jabor Y": "Jabor Y. Inewey",
    "Jabor Y.": "Jabor Y. Inewey",
    "Jack LANG": "Jack Lang",
    "Jack LANG <>": "Jack Lang",
    "Jamie Rosenwald <___________________________________": "Jamie Rosenwald",
    "Jean HUGUEN": "Jean Huguen",
    "Jessica Cadwell, Paralegal": "Jessica Cadwell",
    "Joel": "Joel Dunn",
    "John Connolly Ed.D.": "John Connolly",
    "Joi Ita": "Joichi Ito",
    "Joi Ito": "Joichi Ito",
    "Joi Ito <": "Joichi Ito",
    "Joi Ito <>": "Joichi Ito",
    "Kaczorowski, Monice M.": "Monice M. Kaczorowski",
    "Karp, Brad S": "Brad S. Karp",
    "Kathy": "Kathryn Ruemmler",
    "Kathy Ruemmle": "Kathryn Ruemmler",
    "Kathy Ruemmler": "Kathryn Ruemmler",
    "Kathy Ruemmler <": "Kathryn Ruemmler",
    "Kathy Ruemmler <____________________": "Kathryn Ruemmler",
    "Kathy Ruemmler <_______________________": "Kathryn Ruemmler",
    "Kathy Ruemmler <____________________________-": "Kathryn Ruemmler",
    "Kathy Ruemmler___________________": "Kathryn Ruemmler",
    "Kathy Ruemmlerl": "Kathryn Ruemmler",
    "Katily Ruemmler imumniummu": "Kathryn Ruemmler",
    "Kelly Friendly <>": "Kelly Friendly",
    "Ken Star": "Ken Starr",
    "Ken Starr <": "Ken Starr",
    "Ken Starr <>": "Ken Starr",
    "Ken Starr <__________________": "Ken Starr",
    "Ken Starr__________________________________": "Ken Starr",
    "LH": "Lawrence H. Summers",
    "LHS": "Lawrence H. Summers",
    "LHS <": "Lawrence H. Summers",
    "LHS <>": "Lawrence H. Summers",
    "LHS___________": "Lawrence H. Summers",
    "LHS__________________________": "Lawrence H. Summers",
    "Lawrence H. Summers <>": "Lawrence H. Summers",
    "Lawrence Summers": "Lawrence H. Summers",
    "Lawrence Summers <>": "Lawrence H. Summers",
    "Landon Thomas": "Landon Thomas Jr.",
    "Landon Thomas Jr. <": "Landon Thomas Jr.",
    "Lang, Caroline": "Caroline Lang",
    "Larry": "Larry Summers",
    "Larry Summer": "Larry Summers",
    "Larry Summers -": "Larry Summers",
    "Larry Summers <": "Larry Summers",
    "Larry Summers <>": "Larry Summers",
    "Larry Visosk": "Larry Visoski",
    "Larry Visoski <>": "Larry Visoski",
    "Lawrence Krauss <>": "Lawrence Krauss",
    "Leah Reis-Dennis <1": "Leah Reis-Dennis",
    "Leon Black <IMMIMI": "Leon Black",
    "Lesley Groff <>": "Lesley Groff",
    "Lesley Groff I_____________________________": "Lesley Groff",
    "Lilly Sanchez <___________________": "Lilly Sanchez",
    "Lilly Sanchez I": "Lilly Sanchez",
    "Linda Stone <I_______________________r-": "Linda Stone",
    "Lisa Ne": "Lisa New",
    "Lisa New <1": "Lisa New",
    "Lisa New <>": "Lisa New",
    "Lisa New________________________": "Lisa New",
    "Lvje": "Las Vegas Jewish Experience",
    "Lvjet": "Las Vegas Jewish Experience",
    "MARK TRAMO": "Mark Tramo",
    "MMIIIMIM": "Desconhecido 13",
    "MOMMINNEMUMMIN": "Desconhecido 13",
    "Marc.Kensington": "Marc Kensington",
    "Martin G. Weinberg <": "Martin G. Weinberg",
    "Martin G. Weinberg <>": "Martin G. Weinberg",
    "Martin Weinberg": "Martin G. Weinberg",
    "Martin Weinberg iMiniMIM>": "Martin G. Weinberg",
    "Masha Drokova <________________": "Masha Drokova",
    "Maskin, Eric": "Eric Maskin",
    "Michael Wolff -": "Michael Wolff",
    "Michael Wolff 111111111111111.1111111111.1.1.11111111111111.": "Michael Wolff",
    "Michael Wolff <1.111'": "Michael Wolff",
    "Michael Wolff <1111": "Michael Wolff",
    "Michael Wolff <>": "Michael Wolff",
    "Michael Wolff <________________": "Michael Wolff",
    "Michael Wolff <j____________________________k": "Michael Wolff",
    "Michael Wolff MMMNIMMIMMI": "Michael Wolff",
    "Michael Wolff _______________________________": "Michael Wolff",
    "Michael Wolff______________________": "Michael Wolff",
    "Michael Wolffl": "Michael Wolff",
    "Michael, Charles": "Charles Michael",
    "Miller, Micha": "Micha Miller",
    "Miller, Michael": "Michael Miller",
    "Mohamed Waheed": "Mohammed Waheed Hassan",
    "Mohamed Waheed Hassan": "Mohammed Waheed Hassan",
    "Mosk, Matthew": "Matthew Mosk",
    "Moskowitz, Bennet J.": "Bennet J. Moskowitz",
    "NYTimes.com News Alert": "NYTimes.com (News Alert)",
    "Neal Kassel": "Neal Kassell",
    "Neil Gershenfeld <>": "Neil Gershenfeld",
    "Newsmax. corn": "Newsmax",
    "Niall McCarthy | Statista": "Niall McCarthy",
    "Nowak, Martin A.": "Martin A. Nowak",
    "Ozan Tarman <_____________________": "Ozan Tarman",
    "PETER MANDELSON": "Peter Mandelson",
    "Peter Mandelson <________________________________": "Peter Mandelson",
    "PLI": "Desconhecido 14",
    "Paula": "Desconhecido (Paula)",
    "Palazzolo, Joseph": "Joseph Palazzolo",
    "Parker, Ashley": "Ashley Parker",
    "Parker, Ashley <>": "Ashley Parker",
    "Peggy": "Peggy Siegal",
    "Peggy Siegal <>": "Peggy Siegal",
    "Peggy SiegalliM1111.1.1": "Peggy Siegal",
    "Peter Atti": "Peter Attia",
    "Pickier, Nedra": "Nedra Pickier",
    "Pizzurro, Frank LA": "Frank Pizzurro",
    "Prince Bandar bin Sultan": "Principe Bandar Bin Sultan",
    "Pritzker, Tom": "Tom Pritzker",
    "Nadia": "Desconhecido (Nadia)",
    "Renata B": "Renata Bolotova",
    "Richard Kahn <>": "Richard Kahn",
    "Richard Kahn___________________________": "Richard Kahn",
    "Robert Grusky <>": "Robert Grusky",
    "Robert Kuhn": "Robert Lawrence Kuhn",
    "Robert Kuhn •": "Robert Lawrence Kuhn",
    "Robert L. Kuhn": "Robert Lawrence Kuhn",
    "Robert Trivers <>": "Robert Trivers",
    "Robert Triversi": "Robert Trivers",
    "Rush, George": "George Rush",
    "Rush, George mailto": "George Rush",
    "Scott J. Lin": "Scott J. Link",
    "Sean Banno": "Sean Bannon",
    "Sharon Churcher <>": "Sharon Churcher",
    "Starr, Ken": "Ken Starr",
    "Stephen Hanso": "Stephen Hanson",
    "Steve Bannon <": "Steve Bannon",
    "Steve Bannon <>": "Steve Bannon",
    "Steve Bannon <__________________": "Steve Bannon",
    "Steve Bannon <____________________": "Steve Bannon",
    "Steve Bannor": "Steve Bannon",
    "Steve Hanson <>": "Steve Hanson",
    "Steven Elkman <>": "Steven Elkman",
    "Steven Pfeiffer <_": "Steven Pfeiffer",
    "Steven Pfeiffer <_________________": "Steven Pfeiffer",
    "Stevenhoffenberg": "Steven Hoffenberg",
    "Sullivan, John": "John Sullivan",
    "Tanzi, Rudolph E": "Rudolph E. Tanzi",
    "Thomas Jr., Landon": "Landon Thomas Jr.",
    "homas Jr., Landon <>": "Landon Thomas Jr.",
    "Thomas Jr., Landon <_______________________": "Landon Thomas Jr.",
    "Thomas Jr., Landon <________________________": "Landon Thomas Jr.",
    "Thomas Jr., Landor": "Landon Thomas Jr.",
    "Thomas Jr., Landon <>": "Landon Thomas Jr.",
    "Thorbjon JagIan": "Thorbjørn Jagland",
    "Thorbjon Jagland": "Thorbjørn Jagland",
    "Thorbjon Jagland <>": "Thorbjørn Jagland",
    "Tonja Haddad Coleman <>": "Tonja Haddad Coleman",
    "Vincenzo lozzo": "Vincenzo Lozzo",
    "Weingarten, Reid": "Reid Weingarten",
    "Wolfe, Alexandra": "Alexandra Wolfe",
    "Zimmerman, Malia McLaughlin": "Malia McLaughlin Zimmerman",
    "abuulabass": "Desconhecido (abuulabass)",
    "admin": "Desconhecido (admin)",
    "anasalrasheed": "Anas Al-Rasheed",
    "anasalrasheed1111": "Anas Al-Rasheed",
    "anasalrasheed______________": "Anas Al-Rasheed",
    "aziza alahmadi": "Aziza Alahmadi",
    "drsra": "Desconhecido (drsra)",
    "ed thompson": "Ed Thompson",
    "ehbarak": "Ehud Barak",
    "elisabeth feliho": "Elisabeth Feliho",
    "habebey": "Desconhecido (habebey)",
    "lawkrauss": "Lawrence Krauss",
    "live:linkspirit": "Live: linkspirit",
    "martin Weinberg": "Martin Weinberg",
    "nk.mb": "Desconhecido (nk.mb)",
    "paul krassner": "Paul Krassner",
    "ro": "Desconhecido (ro)",
    "sender name or email": "Desconhecido (sender name or email)",
    "soon yi previn": "Soon-Yi Previn",
    "soon yi previn_________________________": "Soon-Yi Previn",
    "stanpottinger": "Stanley Pottinger",
    "stanpottinger mailto": "Stanley Pottinger",
    "steven hoffenberg": "Steven Hoffenberg",
    "Shaher":"Desconhecido (Shaher)",
    "Sheikh":"Desconhecido (Sheikh)",
    "tamem": "Desconhecido (tamem)",
    "thnx jeff i m praying44": "Desconhecido (thnx jeff i m praying44)"
}

df_saida = df_saida.copy()
df_saida.loc[:, 'de'] = df_saida['de'].replace(mapeamento)

In [28]:
pessoas_de = df_saida['de'].unique()
pessoas_de = sorted(pessoas_de)
for pessoa in pessoas_de:
    print(pessoa)

A Barrett
Afri zp
Al Franken
Al seckel
Alan Dershowitz
Alan Rogers
Alexandra Preate
Alexandra Wolfe
Alireza Ittihadieh
Amanda Ens
Anas Al-Rasheed
Anas Alrasheed
Anders Corr
Andres Serrano
Andrew Friendly
Anil Ambani
Ann Coulter
Annette Witheridge
Ariane de Rothschild
Ashley Parker
Auren Hoffman
Aziza Alahmadi
Barbro C. Ehnbom
Barnaby Marsh
Barry J. Cohen
Benjamin Harnwell
Benjamin Wegg-Prosser
Bennet J. Moskowitz
Bill Siegel
Blanche Christerso
Bloomberg
Bob Crowe
Boris Nikolic
Brad Edwards
Brad S. Karp
Brad Wechsler
Brandon Thompson
Brian Heberlig
Bruce Moskowitz
Bryan Subotnick
CLL
CNS Adam Klasfeld
Caroline Lang
Carolyn Rangel
Cathy Alexander
Cecilia Schött
Cecilia Steen
Charles Michael
Christina Galbraith
Comms Alert
Dan Christensen
Dangene and Jennie Enterprise
Daniel Sabba
Daniel Siad
Darren K. Indyke
Darren lndyke
Dave Hope
David Bianco, Deutsche Bank
David Blaine
David Fiszel
David Grosof
David Haig
David I. Schoen
David Ingram News
David Mitchell
David Pegg
David Schoen
David Stern
David Willis
Deepak Chopra
Desconhecido (Nadia)
Desconhecido (Paula)
Desconhecido (Shaher)
Desconhecido (Sheikh)
Desconhecido (abuulabass)
Desconhecido (admin)
Desconhecido (drsra)
Desconhecido (habebey)
Desconhecido (nk.mb)
Desconhecido (ro)
Desconhecido (sender name or email)
Desconhecido (tamem)
Desconhecido (thnx jeff i m praying44)
Desconhecido 1
Desconhecido 10
Desconhecido 11
Desconhecido 12
Desconhecido 13
Desconhecido 14
Desconhecido 2
Desconhecido 3
Desconhecido 4
Desconhecido 5
Desconhecido 6
Desconhecido 7
Desconhecido 8
Desconhecido 9
Diane Ziman
Dick Cavett
Donald Rubin
Donald Trump
Doug Hope
Dr. Bruce L. Dennis
Dr. David L. Hayes
Ed Boyden
Ed Thompson
Edward Epstein
Edward Rod Larsen
Edyta Wynberg
Ehud Barak
Elisa New
Elisabeth Feliho
Eric Maskin
Eric Roth
Erika Kellerhals
Esneh
Etienne Binant
Eva Pichand
FT Breaking News
Fabrice Aidan
Faith Kates
Fareed Zakaria
Florence Anthony
Frank Pizzurro
Fred Beck
Fred Haddad
GBIU-MideastNews
George Rush
Gerald Barton
Ghislaine Maxwell
Gianni Serazzi
Gino Yu
Google Alerts
Gordon Getty
Greg Farrell
Guy Amico
Gwendolyn Beck
Harry Fisch
Heather Man
House Oversight
How To Academy
Howard Rubenstein
Ian Osborne
Investigative Reporter, FoxNews.com
Jabor Y. Inewey
Jack Browning
Jack Goldberger
Jack Lang
Jacquie Johnson
Jakob Kollhofer
James Drougas
James E. Hill
Jamie Rosenwald
Jason Miller
Jay Lefkowitz
Jean Huguen
Jean Luc Brunel
Jeffrey Epstein
Jennifer Jacquet
Jeremy Rubin
Jesse Kornbluth
Jessica Cadwell
Jide Zeitlin
Joel Dunn
John Brockman
John Connolly
John Page
John Sullivan
Johnny el Hachem
Joichi Ito
Jonathan Farkas
Joscha Bach
Joseph Palazzolo
Joshua Cooper Ramo
Justin Blackhall
Kate Briquelet
Katherine Keating
Kathryn Ruemmler
Kelly Friendly
Ken Starr
Kevin Frost
Keyu Jin
Kirsty Mackenzie
Kristin Andersen
Landon Thomas Jr.
Larry Summers
Larry Visoski
Las Vegas Jewish Experience
Laurie Cameron
Lawrance Visoski
Lawrence H. Summers
Lawrence Krauss
Lawrence Visoski
Leah Reis-Dennis
Leon Black
Lesley Groff
Lilly Sanchez
Linda Pinto
Linda Stone
Lisa New
Lisa Rossi
Live: linkspirit
Lonnie Martin
Magdalena Schuster
Malia McLaughlin Zimmerman
Manuela Wieland
Marc Kensington
Margaret Slattery
Maria Luisa
Maria T. Zuber
Mark Cohen
Mark Green
Mark L. Epstein
Mark Lloyd
Mark Tramo
Marshall E. Eisenberg
Martin A. Nowak
Martin G. Weinberg
Masha Drokova
Matt Williams
Matthew Hiltzik
Matthew Mosk
Melanie Hicken
Melanie Spinella
Melanie Walker
Merwin Dela cruz
Micha Miller
Michael Braun
Michael Greenberg
Michael Miller
Michael Reiter/PalmBeach
Michael Wolff
Mike Cohen
Miles Alexander
Miroslav Lajčák
Mohammed Waheed Hassan
Monice M. Kaczorowski
Morgan Stanley
Moshe Hoffman
NYTimes.com (News Alert)
Nay Gupta
Neal Kassell
Nedra Pickier
Neil Gershenfeld
Newsmax
Niall McCarthy
Nicholas Drinkwater
Nicholas Ribis
Noam Chomsky
Ozan Tarman
Patricia Gonzalez
Paul Barred
Paul Barrett
Paul Krassner
Paul Morris
Paul Prosperi
Paul Schulte
Peggy Siegal
Peter Attia
Peter Mandelson
Peter Thiel
Philip Barden
Philip Levine
Prateek Jain
Principe Bandar Bin Sultan
Purevsuren Lundeg
Ramsey Elkholy
Raw Story Overnight
Rebecca Watson
Reid Hoffman
Reid Weingarten
Renata Bolotova
Richard John Nawrot
Richard Kahn
Richard Merkin
Robert D. Critton Jr.
Robert Grusky
Robert Lawrence Kuhn
Robert Trivers
Ross Gow
Roy Black
Ruberto Israel & Weiner
Rudolph E. Tanzi
Scoop Notifications
Scott J. Link
Sean Bannon
Sean J. Lancaster
Shanson900
Sharon Churcher
Sidney Blumenthal
Skip Rimer
SmartBrief on Business & Politics
Soon-Yi
Soon-Yi Previn
Stanley Pottinger
Stanley Rosenberg
Stephanie
Stephen Alexander
Stephen Hanson
Stephen J. Immelt
Steve Bannon
Steve Hanson
Steven Elkman
Steven Hoffenberg
Steven Pfeiffer
Steven Sinofsky
Stewart Oldfield
Sultan Bin Sulayem
Tamem
Terje Rod-Larsen
Terry Kafka
Tesley Groff
The Daily Beast: PM Cheat Sheet
The Washington Post
Thomas D. Williams
Thomas L. Friedman
Thorbjørn Jagland
Tim Zagat
Timothy Jones
Tom Barrack Private
Tom Pritzker
Tonja Haddad Coleman
Tyler Shears
Valeria Chomsky
Vincenzo Lozzo
Vinit Sahni
Vinoda Basnayake
William L. Blum
William McLendon
Zubair Khan

Agora olhando para a coluna 'para':

In [29]:
pessoas_para = df_saida['para'].unique()
pessoas_para = sorted(pessoas_para)
for pessoa in pessoas_para:
    print(pessoa)

#L&W BD PR US
'Cavan Mahony'
'Cavan mahony'
'Esneh'
'Jean'
'Martin G. Weinberg'
-11>
111110
<1111111
<MEMIN
ANN BAISE
AdeR
Adrienne Ross
Al seckel
Al seckel <
Alan Dershowitz
Alan Fraade
Alan M. Dershowitz
Alan M. Dershowitz Martin Weinberg
Alan Rogers
Alex
Alex LA
Alex.Family Pines
Alexander Marlow
Alexander Marlow <>
Alexandra
Alireza ITTIHADIEH
Alireza Ittihadieh
Allen West
Amanda
Anas Alrasheed
Andreas Kraus
Andres Serrano
Anna Dreber
Anthony
Anula Jayasuriya
Apparently
Ariane de Rothschild
Authoritarian Influence
Authoritarian Influence <MIM
Balin, Robert
Barb Cowles
Barbro C Ehnbom
Barbro Ehnbom
Barnaby Marsh
Barry J. Cohen
Barry J. Cohen <>
Barry Josephson
Bauer
Bauer, Steve SF-BR
Bella Klein
Belle Gray
Ben Sosenko
Benjamin Wegg-Prosser
Bennett Schmidt
Bill Prezant
Bill Siegel
Bob & Sandy
Bob Crowe
Bob Fass
Bobby McCormick
Boris Nikolic
Brad Edwards
Brad S
Brad S <___________________________
Brad S Karp
Brad S Karp__________________________
Brad Wechsler
Bradley J. Edwards
Brandon Thompson
Brett D. Jaffe
Brian Baker
Bridges Hague
Bruce Moskowitz
Bruno, Nicole NY
CLL
Caroline
Caroline Lang
Cartwright, Lachlan
Caryl Ratner
Charles
Cheikh Tidiane Sy
Cheves
Cheves, Belle
Christina Galbraith
Clair Brown
Clive Crook
Conchita Sarnoff
Connie Zaguirre
DAN CHRISTENSEN
DANNY GOLDBERG
DAVID SCHOEN
Dan Christensen
Dan Fleuette
Dane Stangler
Dangene and Jennie Enterprise
Daniel CC
Daniel Dawson
Daniel Siad
Danny Goldberg
Darren
Darren Indyk
Darren Indyke
Darren K.
Darren lndyke
Dave Hope
David
David Blaine
David Darst
David Grosof
David Schoen
David Stern
Dean OC
Debbie Fein
Deepak Chopra
Diane Ziman
Ditsa Pines
Dixon, Timothy
Dlugash, Alan
Donald Trump
Dunlavey
Ed
Ed Boyden
Ed Hammer
Edward B. Reynolds, Jr.
Edward Rod Larsen
Ehud Barak
Eisenberg
El Hadji Amadou Sall
Ens
Epstein Jeffrey
Eric
Eric Roth
Erika Kellerhals
Esq.
Etienne Binant
Evan Smith
Fabrice Aidan
Faith Kate
Faith Kates
Fanell Red
Fareed Zakaria GPS
Forrest Miller - adj kearsarge
Frances Martel
Francis
Francis Derby
Frau Dichand
Fred Haddad
Friend
Friends and Family
Fwd: T V
G G
G Maxwell
GMAX
GREG FARRELL BLOOMBERG/ NEWSROOM:
Gary Gross
Gary H. BaisallillW>
Gary H. Baise
Gates Foundation
George Henderson
George Krassner
Gerald B. Lefcourt
Gerald Barton
Ghislaine Maxwell
Gianni Serazzi
Gino Yu
Gmax
Gordon Getty
Gray, Alex
Greenberg
Greenberg, Jeffrey LA-NY
Greg LA
Gwendolyn
Gwendolyn Beck
HOUSE OVERSIGHT
HOUSE OVERSIGHT 031039
Haig
Halligan
Harris
Harris, Nicole CH
Harry Fisch
Heather Mann
Henry hortenstine
Hill
Holly Krassner Dawson
Howard Rubenstein
IIII
I_____________________________
Ian Osborne
Ihsoffice
Ihsofficel
Immelt
Indyke
Inside Job 2010
JEE
JONATHAN FARKAS
JR Stambaugh
Jabor Y
Jabor Y.
Jabor Y. INEWEI
Jack Goldberger
Jack LANG
Jack Lang
Jackie Perczek
Jacquie Johnson
Jakob Kollhofer
James E.
James Ramsey
Jamie
Januiz Banasiak
Jay Lefkowitz
Jean HUGUEN
Jean Luc Brune
Jean Luc Brunel
Jeffery Edwards
Jeffrey
Jeffrey Epstein
Jeffrey LA-NY
Jeffrey&j effreyep stein. org
Jennings
Jennings, Alex LA
Jeremy Rubin
Jesse Kornbluth
Jessica Cadwell
Jide Zeitlin
Jim
Joe Biden
Joe Nordgaard
Joel
Joel Dunn
John Castrucci
John Mallen
John Stepek
Joi
Joi Ito
Joichi Ito
Joichi Joi Ito
Jonathan Farkas
Joseph Bernstein
Joseph Vinciguerra
Joshua Cooper Ramo
Jul Romer
Karp
Kathy
Kathy DC
Kathy Ruemmle
Kathy Ruemmler
Kathy Ruemmler Darren lndyke Martin Weinberg
Kathy Ruemmler Darren lndyke • Martin Weinberg
Kathy Ruemmler Martin Weinberg Alan Dershowitz
Kathy Ruemmler f
Kathy Ruemmler__________________
Kathy Ruemmlerl
Kelly Friendly
Ken
Ken Star
Ken Starr
Ken Starr <>
Kensington2
Kevin Bright
Kevin Frost
Keyu Jin
Kimberly Homan
LHS
LHS _____________________________
Lajcak Miroslav/MINISTER/MZV
Lajcak Miroslay/MINISTER/MZV
Landon Thomas
Landon Thomas Jr
Landon Thomas Jr.
Landon Thomas<_____________________
Lang
Lang, Caroline
Larry
Larry Summer
Larry Summers
Larry Visosk
Larry Visoski
Larry Visoski <>
Lawrance Visoski
Lawrence
Lawrence H.
Lawrence H. <>
Lawrence H. Summers <>
Lawrence Henry Summers
Lawrence Henry Summers <>
Lawrence I.
Lawrence Krauss
Lawrence Summers
Lawrence Summers '11
Lawrence Summers <>
Lawrence Visoski
Leah Reis-Dennis
Lee Quarnstrom
Leon Black
Lesley Groff
Lesley Groff <
Lesley Groff <>
Lesley Groff MMIIII
Lesley Groffl
Leslie
Lila Walker
Lilly Ann Sanchez
Lilly Sanchez
Linda PINTO
Linda Stone
Linda W. Grossman
Lisa Ne
Lisa New
Lisa albert
Liz Hartley
Louella Rabuyo
LouellaRabuycll Januiz Banasiak
Louis
Lvjet
Lyn fontanilla
Lynnie Tofte Fass
MD
MII
MMIIIIIMIMI
MMIIIMIM
MOMMINNEMUMMIN
Mahle, Melissa
Marc.Kensington
Marcie brown
Margie
Marguerite Atkins
Maria Luisa
Mariana Idikowska
Marie Moneysmith
Mark L. Epstein
Mark Lloyd
Mark epstein
Marshall E.
Marshall Funk
Martin A.
Martin A. <MIIMINI
Martin G Weinberg
Martin G. Weinberg
Martin Nowak
Martin Weinberg
Martin Weinberg Esq
Martin Weinberg dkiesq
Martin Weinberg<__________________
Masha Drokova
Maskin
Matt Ridley
Matt Williams
Matthew Hiltzik
Mayor
Melanie Spinel!
Melanie Spinella
Melanie Spinella <>
Melanie Walker
Michael
Michael Braun
Michael Braun <i
Michael Greenberg
Michael J. Pike
Michael S. Sitrick
Michael Simmons
Michael Wolff
Michael Woli
Mike Cagney
Mike Sitrick
Miles Alexander
Miller
Miller, Glen
Miller, Michael
Mohamed Seydou Diagne
Mohamed Waheed
Mohamed Waheed Hassan
Mohebbi
Mohebbi, Nima LA
Monika Gruter Cheney
Moore
Moore, Wendy OC
Morad Tahbaz
Mortimer Zuckerman
Moshe Hoffman
Ms. Yvette Robbins
NY Max
Nadia
Nancy Cain
Nate mcclain
Neal Kassel
Neal Kassell
Neil Gershenfeld
Neil Gershenfeld <>
Neil anderson
Nicholas
Nicholas Gahhos
Nicholas Ribis
Nick Pyke
Nicole CH
Nima LA
Noam Chomsky
Norman Finkelstein
Nowak
Oliver Goodenough
Oliver Lane
Owen Blicksilver
PETER MANDELSON
PETER MANDELSON.
Packer Families
Paralegal
Paul Barrett
Paul Krassner
Paul Morris
Paul Morris/db/
Paul Schierenbeck
Paul Schulte
Paul Zak
Paula
Peggy
Peggy Siega
Peggy Siegal
Peter Attia
Peter Mandelson
Peter Mandelson BT
Peter Thiel
Philip Barden
Philip Kafka
Players2 .
Preate Alexandra
Pritzker
Prosperi Paul
Purevsuren Lundeg
RALPH BERNSTEIN
Raafat Alsabbagh
Rafael Bardaji
Raheem Kassam
Ramsey Elkholy
Rebecca Drescher
Rebecca Watson
Reid
Reid Hoffman
Reid Weingarten
Renata B
Renata Bolotova
Rich Kahn
Rich Kahn IMMIMMIIIIMII;
Richard Barnnet
Richard Joshi
Richard Joslin
Richard Kahn
Richard Kahn <>
Richard Kahn_______________________
Richard Kahn______________________________
Richard Merkin
Richerson, Peter J
Richman
Richman, Lawrence
Rob Hanson
Robert A. Solomon
Robert D. Critton Jr.
Robert D. Critton Jr. • Jessica Cadwell
Robert Gold
Robert Kuhn
Robert Trivers
Robins
Robins, Greg LA
Roger Edelen
Ron Bailey
Ross Gow
Roy Black
Ruemmler
Ruemmler, Kathy DC
Sam/Walli Leff
Samuel Leff
Schecter
Schecter, Daniel CC
Scott J. Link
Scott Stambaugh
Scott Stambauh
Sean Bannon
Seche, Stephen A.
Shaher
Sheikh
Shlomit Dekel
Silverman
Silverman, Nicholas
Soon Yi Previn
Soon-Yi
Stanley Rosenberg
Starr
Stephen Hanso
Stephen Hanson
Stephen J.
Stephen Rubin
Steve Bannon
Steve Bannon <>
Steve Bannon I
Steve Bannon<
Steve Bannon<1____________________
Steve Bannon<>
Steve Bannor
Steve SF-BR
Steven Gaydos
Steven Pfeiffer
Stewart Oldfield
Subotnick Stuart
Subotnick Stuart 11111111111111111111>
Sultan Bin Sulayem
Summers
Suzanne Pettit
Tazia Smith
Terje Rod-Larsen
Terry Anderson
Terry Kafka
Thorbjon Jaglan
Thorbjon Jagland
Tim Kane
Tim Zagat
Tina Brown
Tom
Tom Barrack Privat
Tom Barrack Private
Tom Pritzker
Tom Turrin
Tonja Haddad Coleman
Torla Haddad Coleman
Tracie Morrissey
Tyler Shears
Unspecified
Vahe Stepanian
Val sherman
Valeria Chomsky
Vinit Sahni
Vinit Sahni/db/
Vinoda Basnayake
Warren Eisenstein
Weingarten
Weingarten, Reid
Wendy OC
William L. Blum
William Riley
Wine
Wine, Jamie NY
Wolfe
Zubair Khan
___________________________
____________________________
_______________________________
anasalrasheed
anil.ambani
behnborn
dkiesq
ehud barak___________________________
elisabeth feliho
habebey
jac
janet kafka
jean.huguen
jeffrey E.
john zouzelka-cell
lawkrauss
lhsoffic
lhsoffice
live:linkspirit
michael
nate white
nicholas.ribis
paul krassner
paul prosperi
recipient name or email
rita hortenstine
ro
rote
soon yi previ
soon yi previn
taal safdie
tamem
thnx jeff i m praying44
undisclosed-recipients:
uri fouzailov

Vamos aplicar também um mapeamento específico, mas antes disso vamos tentar reutilizar o anterior.

In [30]:
df_saida = df_saida.copy()
df_saida.loc[:, 'para'] = df_saida['para'].replace(mapeamento)

In [31]:
pessoas_para = df_saida['para'].unique()
pessoas_para = sorted(pessoas_para)
for pessoa in pessoas_para:
    print(pessoa)

#L&W BD PR US
'Cavan Mahony'
'Cavan mahony'
'Esneh'
'Jean'
'Martin G. Weinberg'
111110
<MEMIN
ANN BAISE
AdeR
Adrienne Ross
Al seckel
Al seckel <
Alan Dershowitz
Alan Fraade
Alan M. Dershowitz
Alan M. Dershowitz Martin Weinberg
Alan Rogers
Alex
Alex LA
Alex.Family Pines
Alexander Marlow
Alexander Marlow <>
Alexandra
Alireza Ittihadieh
Allen West
Amanda
Anas Al-Rasheed
Anas Alrasheed
Andreas Kraus
Andres Serrano
Anil Ambani
Anna Dreber
Anthony
Anula Jayasuriya
Apparently
Ariane de Rothschild
Authoritarian Influence
Authoritarian Influence <MIM
Balin, Robert
Barb Cowles
Barbro C. Ehnbom
Barnaby Marsh
Barry J. Cohen
Bauer
Bauer, Steve SF-BR
Bella Klein
Belle Gray
Ben Sosenko
Benjamin Wegg-Prosser
Bennett Schmidt
Bill Prezant
Bill Siegel
Bob & Sandy
Bob Crowe
Bob Fass
Bobby McCormick
Boris Nikolic
Brad Edwards
Brad S
Brad S <___________________________
Brad S Karp
Brad S Karp__________________________
Brad Wechsler
Bradley J. Edwards
Brandon Thompson
Brett D. Jaffe
Brian Baker
Bridges Hague
Bruce Moskowitz
Bruno, Nicole NY
CLL
Caroline
Caroline Lang
Cartwright, Lachlan
Caryl Ratner
Charles
Cheikh Tidiane Sy
Cheves
Cheves, Belle
Christina Galbraith
Clair Brown
Clive Crook
Conchita Sarnoff
Connie Zaguirre
DANNY GOLDBERG
Dan Christensen
Dan Fleuette
Dane Stangler
Dangene and Jennie Enterprise
Daniel CC
Daniel Dawson
Daniel Siad
Danny Goldberg
Darren
Darren Indyk
Darren K.
Darren K. Indyke
Darren lndyke
Dave Hope
David Bianco, Deutsche Bank
David Blaine
David Darst
David Grosof
David Schoen
David Stern
Dean OC
Debbie Fein
Deepak Chopra
Desconhecido (Nadia)
Desconhecido (Paula)
Desconhecido (Shaher)
Desconhecido (Sheikh)
Desconhecido (habebey)
Desconhecido (ro)
Desconhecido (tamem)
Desconhecido (thnx jeff i m praying44)
Desconhecido 1
Desconhecido 11
Desconhecido 12
Desconhecido 13
Desconhecido 5
Diane Ziman
Ditsa Pines
Dixon, Timothy
Dlugash, Alan
Donald Trump
Dunlavey
Ed Boyden
Ed Hammer
Edward B. Reynolds, Jr.
Edward Rod Larsen
Ehud Barak
Eisenberg
El Hadji Amadou Sall
Elisabeth Feliho
Ens
Epstein Jeffrey
Eric
Eric Roth
Erika Kellerhals
Esq.
Etienne Binant
Evan Smith
Fabrice Aidan
Faith Kates
Fanell Red
Fareed Zakaria
Forrest Miller - adj kearsarge
Frances Martel
Francis
Francis Derby
Frau Dichand
Fred Haddad
Friend
Friends and Family
Fwd: T V
G G
GREG FARRELL BLOOMBERG/ NEWSROOM:
Gary Gross
Gary H. BaisallillW>
Gary H. Baise
Gates Foundation
George Henderson
George Krassner
Gerald B. Lefcourt
Gerald Barton
Ghislaine Maxwell
Gianni Serazzi
Gino Yu
Gordon Getty
Gray, Alex
Greenberg
Greenberg, Jeffrey LA-NY
Greg LA
Gwendolyn Beck
HOUSE OVERSIGHT 031039
Haig
Halligan
Harris
Harris, Nicole CH
Harry Fisch
Heather Man
Henry hortenstine
Hill
Holly Krassner Dawson
House Oversight
Howard Rubenstein
IIII
Ian Osborne
Ihsoffice
Ihsofficel
Immelt
Indyke
Inside Job 2010
JR Stambaugh
Jabor Y. Inewey
Jack Goldberger
Jack Lang
Jackie Perczek
Jacquie Johnson
Jakob Kollhofer
James E.
James Ramsey
Jamie
Januiz Banasiak
Jay Lefkowitz
Jean Huguen
Jean Luc Brune
Jean Luc Brunel
Jeffery Edwards
Jeffrey
Jeffrey Epstein
Jeffrey LA-NY
Jeffrey&j effreyep stein. org
Jennings
Jennings, Alex LA
Jeremy Rubin
Jesse Kornbluth
Jessica Cadwell
Jide Zeitlin
Jim
Joe Biden
Joe Nordgaard
Joel Dunn
John Castrucci
John Mallen
John Stepek
Joi
Joichi Ito
Joichi Joi Ito
Jonathan Farkas
Joseph Bernstein
Joseph Vinciguerra
Joshua Cooper Ramo
Jul Romer
Karp
Kathryn Ruemmler
Kathy DC
Kathy Ruemmler Darren lndyke Martin Weinberg
Kathy Ruemmler Darren lndyke • Martin Weinberg
Kathy Ruemmler Martin Weinberg Alan Dershowitz
Kathy Ruemmler f
Kathy Ruemmler__________________
Kelly Friendly
Ken
Ken Starr
Kensington2
Kevin Bright
Kevin Frost
Keyu Jin
Kimberly Homan
LHS _____________________________
Lajcak Miroslav/MINISTER/MZV
Lajcak Miroslay/MINISTER/MZV
Landon Thomas Jr
Landon Thomas Jr.
Landon Thomas<_____________________
Lang
Larry Summers
Larry Visoski
Las Vegas Jewish Experience
Lawrance Visoski
Lawrence
Lawrence H.
Lawrence H. <>
Lawrence H. Summers
Lawrence Henry Summers
Lawrence Henry Summers <>
Lawrence I.
Lawrence Krauss
Lawrence Summers '11
Lawrence Visoski
Leah Reis-Dennis
Lee Quarnstrom
Leon Black
Lesley Groff
Lesley Groff <
Lesley Groff MMIIII
Lesley Groffl
Leslie
Lila Walker
Lilly Ann Sanchez
Lilly Sanchez
Linda PINTO
Linda Stone
Linda W. Grossman
Lisa New
Lisa albert
Live: linkspirit
Liz Hartley
Louella Rabuyo
LouellaRabuycll Januiz Banasiak
Louis
Lyn fontanilla
Lynnie Tofte Fass
MD
MII
MMIIIIIMIMI
Mahle, Melissa
Marc Kensington
Marcie brown
Margie
Marguerite Atkins
Maria Luisa
Mariana Idikowska
Marie Moneysmith
Mark L. Epstein
Mark Lloyd
Mark epstein
Marshall E.
Marshall Funk
Martin A.
Martin A. <MIIMINI
Martin G Weinberg
Martin G. Weinberg
Martin Nowak
Martin Weinberg Esq
Martin Weinberg dkiesq
Martin Weinberg<__________________
Masha Drokova
Maskin
Matt Ridley
Matt Williams
Matthew Hiltzik
Mayor
Melanie Spinel!
Melanie Spinella
Melanie Spinella <>
Melanie Walker
Michael
Michael Braun
Michael Braun <i
Michael Greenberg
Michael J. Pike
Michael Miller
Michael S. Sitrick
Michael Simmons
Michael Wolff
Michael Woli
Mike Cagney
Mike Sitrick
Miles Alexander
Miller
Miller, Glen
Mohamed Seydou Diagne
Mohammed Waheed Hassan
Mohebbi
Mohebbi, Nima LA
Monika Gruter Cheney
Moore
Moore, Wendy OC
Morad Tahbaz
Mortimer Zuckerman
Moshe Hoffman
Ms. Yvette Robbins
NY Max
Nancy Cain
Nate mcclain
Neal Kassell
Neil Gershenfeld
Neil anderson
Nicholas
Nicholas Gahhos
Nicholas Ribis
Nick Pyke
Nicole CH
Nima LA
Noam Chomsky
Norman Finkelstein
Nowak
Oliver Goodenough
Oliver Lane
Owen Blicksilver
PETER MANDELSON.
Packer Families
Paralegal
Paul Barrett
Paul Krassner
Paul Morris
Paul Morris/db/
Paul Schierenbeck
Paul Schulte
Paul Zak
Peggy Siega
Peggy Siegal
Peter Attia
Peter Mandelson
Peter Mandelson BT
Peter Thiel
Philip Barden
Philip Kafka
Players2 .
Preate Alexandra
Pritzker
Prosperi Paul
Purevsuren Lundeg
RALPH BERNSTEIN
Raafat Alsabbagh
Rafael Bardaji
Raheem Kassam
Ramsey Elkholy
Rebecca Drescher
Rebecca Watson
Reid
Reid Hoffman
Reid Weingarten
Renata Bolotova
Rich Kahn
Rich Kahn IMMIMMIIIIMII;
Richard Barnnet
Richard Joshi
Richard Joslin
Richard Kahn
Richard Kahn_______________________
Richard Kahn______________________________
Richard Merkin
Richerson, Peter J
Richman
Richman, Lawrence
Rob Hanson
Robert A. Solomon
Robert D. Critton Jr.
Robert D. Critton Jr. • Jessica Cadwell
Robert Gold
Robert Lawrence Kuhn
Robert Trivers
Robins
Robins, Greg LA
Roger Edelen
Ron Bailey
Ross Gow
Roy Black
Ruemmler
Ruemmler, Kathy DC
Sam/Walli Leff
Samuel Leff
Schecter
Schecter, Daniel CC
Scott J. Link
Scott Stambaugh
Scott Stambauh
Sean Bannon
Seche, Stephen A.
Shlomit Dekel
Silverman
Silverman, Nicholas
Soon Yi Previn
Soon-Yi
Soon-Yi Previn
Stanley Rosenberg
Starr
Stephen Hanson
Stephen J.
Stephen Rubin
Steve Bannon
Steve Bannon I
Steve Bannon<
Steve Bannon<1____________________
Steve Bannon<>
Steve SF-BR
Steven Gaydos
Steven Pfeiffer
Stewart Oldfield
Subotnick Stuart
Subotnick Stuart 11111111111111111111>
Sultan Bin Sulayem
Summers
Suzanne Pettit
Tazia Smith
Terje Rod-Larsen
Terry Anderson
Terry Kafka
Thorbjon Jaglan
Thorbjørn Jagland
Tim Kane
Tim Zagat
Tina Brown
Tom
Tom Barrack Privat
Tom Barrack Private
Tom Pritzker
Tom Turrin
Tonja Haddad Coleman
Torla Haddad Coleman
Tracie Morrissey
Tyler Shears
Unspecified
Vahe Stepanian
Val sherman
Valeria Chomsky
Vinit Sahni
Vinit Sahni/db/
Vinoda Basnayake
Warren Eisenstein
Weingarten
Wendy OC
William L. Blum
William Riley
Wine
Wine, Jamie NY
Wolfe
Zubair Khan
___________________________
____________________________
_______________________________
behnborn
dkiesq
ehud barak___________________________
jac
janet kafka
jean.huguen
jeffrey E.
john zouzelka-cell
lhsoffic
lhsoffice
michael
nate white
nicholas.ribis
paul prosperi
recipient name or email
rita hortenstine
rote
soon yi previ
taal safdie
undisclosed-recipients:
uri fouzailov

Aplicando o novo mapeamento:

In [56]:
mapeamento_para = {
    "#L&W BD PR US": "L&W Supply: Commercial Building and Construction Materials",
    "Cavan Mahony": "Cavan Mahony",
    "111110": "Desconhecido 15",
    "<MEMIN": "Desconhecido 13",
    "ANN BAISE": "Desconhecido (ANN BAISE)",
    "AdeR": "Desconhecido (AdeR)",
    "Al seckel": "Al Seckel",
    "Al seckel <": "Al Seckel",
    "Alan M. Dershowitz": "Alan Dershowitz",
    "Alan M. Dershowitz Martin Weinberg": "Alan Dershowitz",
    "Alex": "Alex LA",
    "Alex.Family Pines": "Alex (Family Pines)",
    "Alexander Marlow <>": "Alexander Marlow",
    "Alexandra": "Alexandra Wolfe",
    "Amanda": "Amanda Ens",
    "Anas Alrasheed": "Anas Al-Rasheed",
    "Apparently": "Desconhecido (Apparently)",
    "Authoritarian Influence": "Desconhecido (Authoritarian Influence)",
    "Authoritarian Influence <MIM": "Desconhecido (Authoritarian Influence)",
    "Balin, Robert": "Robert Balin",
    "Bauer, Steve SF-BR": "Steve Bauer",
    "Bauer": "Steve Bauer",
    "Brad S": "Brad S. Karp",
    "Brad S <___________________________": "Brad S. Karp",
    "Brad S Karp": "Brad S. Karp",
    "Brad S Karp__________________________": "Brad S. Karp",
    "Bruno, Nicole NY": "Nicole Bruno",
    "Caroline": "Caroline Lang",
    "Cartwright, Lachlan": "Lachlan Cartwright",
    "Charles": "Desconhecido (Charles)",
    "Cheves, Belle": "Belle Cheves",
    "DANNY GOLDBERG": "Danny Goldberg",
    "Daniel CC": "Desconhecido (Daniel CC)",
    "Darren": "Darren K. Indyke",
    "Darren Indyk": "Darren K. Indyke",
    "Darren K.": "Darren K. Indyke",
    "Darren lndyke": "Darren K. Indyke",
    "Dean OC": "Desconhecido (Dean OC)",
    "Dixon, Timothy": "Timothy Dixon",
    "Dlugash, Alan": "Alan Dlugash",
    "Edward B. Reynolds, Jr.": "Edward B. Reynolds Jr.",
    "Eisenberg": "Marshall E. Eisenberg",
    "Ens": "Amanda Ens",
    "Epstein Jeffrey": "Jeffrey Epstein",
    "Eric": "Eric Roth",
    "Esq.": "Desconhecido(Esq.)",
    "Forrest Miller - adj kearsarge": "Forrest Miller",
    "Francis": "Francis Derby",
    "Friend": "Friends and Family",
    "Fwd: T V": "Desconhecido 16",
    "G G": "Gary Gross",
    "GREG FARRELL BLOOMBERG/ NEWSROOM:": "Greg Farrell",
    "Gary H. BaisallillW>": "Gary H. Baise",
    "Gray, Alex": "Alex Gray",
    "Greenberg": "Jeffrey Greenberg",
    "Greg LA": "Desconhecido(Greg LA)",
    "Gwendolyn": "Gwendolyn Beck",
    "HOUSE OVERSIGHT 031039": "House Oversight",
    "Haig": "Desconhecido (Haig)",
    "Halligan": "Desconhecido (Halligan)",
    "Harris, Nicole CH": "Nicole Harris",
    "Harris": "Harris, Nicole CH",
    "Henry hortenstine": "Henry Hortenstine",
    "Hill": "Desconhecido (Hill)",
    "IIII": "Desconhecido 17",
    "Ihsoffice": "IHS Offices",
    "Ihsofficel": "IHS Offices",
    "Immelt": "Jeff Immelt",
    "Indyke": "Darren K. Indyke",
    "Inside Job 2010": "Inside Job (2010)",
    "JR Stambaugh": "Stambaugh Jr.",
    "Jabor Y.": "Jabor Y. Inewey",
    "Jamie": "Jamie Rosenwald",
    "Jean Luc Brunel": "Jean Luc Brune",
    "Jeffrey": "Desconhecido (Jeffrey)",
    "Jeffrey&j effreyep stein. org": "jeffreyepstein.org",
    "Jennings, Alex LA": "Alex Jennings",
    "Jennings": "Alex Jennings",
    "Jim": "Desconhecido (Jim)",
    "Joi": "Joichi Ito",
    "Joichi Ito": "Joichi Ito",
    "Joichi Joi Ito": "Joichi Ito",
    "Karp": "Brad S. Karp",
    "Kathy DC": "",
    "Kathy Ruemmler Darren lndyke Martin Weinberg": "Kathryn Ruemmler",
    "Kathy Ruemmler Darren lndyke • Martin Weinberg": "Kathryn Ruemmler",
    "Kathy Ruemmler Martin Weinberg Alan Dershowitz": "Kathryn Ruemmler",
    "Kathy Ruemmler f": "Kathryn Ruemmler",
    "Kathy Ruemmler__________________": "Kathryn Ruemmler",
    "Ken": "Ken Starr",
    "Kensington2": "Marc Kensington",
    "LHS": "Lawrence H. Summers",
    "Lajcak Miroslav/MINISTER/MZV": "Miroslav Lajčák",
    "Lajcak Miroslay/MINISTER/MZV": "Miroslav Lajčák",
    "Landon Thomas Jr": "Landon Thomas Jr.",
    "Landon Thomas<_____________________": "Landon Thomas Jr.",
    "Lang": "Jack Lang",
    "Larry Summers": "Lawrence H. Summers",
    "LHS _____________________________": "Lawrence H. Summers",
    "Lawrence": "Lawrence H. Summers",
    "Lawrence H.": "Lawrence H. Summers",
    "Lawrence H. <>": "Lawrence H. Summers",
    "Lawrence Henry Summers": "Lawrence H. Summers",
    "Lawrence Henry Summers <>": "Lawrence H. Summers",
    "Lawrence Summers '11": "Lawrence H. Summers",
    "Lesley Groff <": "Lesley Groff",
    "Lesley Groff MMIIII": "Lesley Groff",
    "Lesley Groffl": "Lesley Groff",
    "Leslie": "Lesley Groff",
    "Lilly Sanchez": "Lilly Ann Sanchez",
    "Linda PINTO''": "Linda Pinto",
    "LouellaRabuycll Januiz Banasiak": "Desconhecido (LouellaRabuycll Januiz Banasiak)",
    "Louis": "Desconhecido (Louis)",
    "Lisa albert": "Lisa Albert",
    "Lyn fontanilla": "Lyn Fontanilla",
    "MD": "Masha Drokova",
    "MMIIIIIMIMI": "Michael Wolff",
    "MII": "Desconhecido 18",
    "Mahle, Melissa": "Melissa Mahle",
    "Margie": "Desconhecido (Margie)",
    "Mark epstein": "Mark Epstein",
    "Martin A. <MIIMINI": "Martin A.",
    "Martin G Weinberg": "Martin G. Weinberg",
    "Martin Weinberg Esq": "Martin G. Weinberg",
    "Martin Weinberg dkiesq": "Martin G. Weinberg",
    "Martin Weinberg<__________________": "Martin G. Weinberg",
    "Maskin": "Eric Maskin",
    "Mayor": "Desconhecido (Mayor)",
    "Melanie Spinel!": "Melanie Spinella",
    "Melanie Spinella <>": "Melanie Spinella",
    "Michael": "Michael Braun",
    "Michael Braun <i": "Michael Braun",
    "Michael Woli": "Michael Wolff",
    "Miller, Glen": "Glen Miller",
    "Miller": "Glen Miller",
    "Mohebbi, Nima LA": "Nima Mohebbi",
    "Mohebbi": "Nima Mohebbi",
    "Moore, Wendy": "Wendy Moore",
    "Moore": "Wendy Moore",
    "Nadia": "Desconhecido (Nadia)",
    "Nate mcclain": "Nate Mcclain",
    "Neil anderson": "Neil Anderson",
    "Nicholas": "Nicholas Gahhos",
    "Nima": "Nima Mohebbi",
    "Nowak": "Martin A. Nowak",
    "Nicole CH": "Nicole Bruno",
    "PETER MANDELSON.": "Peter Mandelson",
    "Paralegal": "Desconhecido (Paralegal)",
    "Paul Morris/db/": "Paul Morris",
    "Paula": "Desconhecido (Paula)",
    "Peggy Siega": "Peggy Siegal",
    "Peter Mandelson BT": "Peter Mandelson",
    "Players2 .": "Desconhecido (Players2)",
    "Pritzker": "Tom Pritzker",
    "RALPH BERNSTEIN": "Ralph Bernstein",
    "Reid": "Reid Hoffman",
    "Rich Kahn IMMIMMIIIIMII;": "Rich Kahn",
    "Richard Kahn_______________________": "Richard Kahn",
    "Richard Kahn______________________________": "Richard Kahn",
    "Richerson, Peter J": "Peter J. Richerson",
    "Richman, Lawrence": "Lawrence Richman",
    "Richman": "Lawrence Richman",
    "Robert D. Critton Jr. • Jessica Cadwell": "Jessica Cadwell",
    "Robins, Greg LA": "Greg Robins",
    "Robins": "Greg Robins",
    "Ruemmler": "Kathryn Ruemmler",
    "Ruemmler, Kathy DC": "Kathryn Ruemmler",
    "Sam/Walli Leff": "Samuel Leff",
    "Schecter, Daniel CC": "Daniel Schecter",
    "Schecter": "Daniel Schecter",
    "Scott Stambauh": "Scott Stambaugh",
    "Seche, Stephen A.": "Stephen A. Seche",
    "Silverman, Nicholas": "Nicholas Silverman",
    "Silverman": "Nicholas Silverman",
    "Soon Yi Previn": "Soon-Yi Previn",
    "Soon-Yi": "Soon-Yi Previn",
    "Soon-Yi Previn": "Soon-Yi Previn",
    "Starr": "Ken Starr",
    "Steve Bannon I": "Steve Bannon",
    "Steve Bannon<": "Steve Bannon",
    "Steve Bannon<1____________________": "Steve Bannon",
    "Steve Bannon<>": "Steve Bannon",
    "Steve SF-BR": "Steve Bauer",
    "Subotnick Stuart 11111111111111111111>": "Subotnick Stuart",
    "Summers": "Lawrence H. Summers",
    "Thorbjon Jaglan": "Thorbjørn Jagland",
    "Tom": "Tom Barrack",
    "Tom Barrack Privat": "Tom Barrack",
    "Tom Barrack Private": "Tom Barrack",
    "Torla Haddad Coleman": "Tonja Haddad Coleman",
    "Unspecified": "Desconhecido 19",
    "Val sherman": "Val Sherman",
    "Vinit Sahni/db/": "Vinit Sahni",
    "Weingarten": "Reid Weingarten",
    "Wendy OC": "Wendy Moore",
    "Wine, Jamie NY": "Jamie Wine",
    "Wine": "Jamie Wine",
    "Wolfe": "Alexandra Wolfe",
    "___________________________": "Desconhecido 20",
    "____________________________": "Desconhecido 21",
    "_______________________________": "Desconhecido 22",
    "behnborn": "Desconhecido (behnborn)",
    "dkiesq": "Martin G. Weinberg",
    "ehud barak___________________________": "Ehud Barak",
    "jac": "Desconhecido (jac)",
    "janet kafka": "Janet Kafka",
    "jean.huguen": "Jean Huguen",
    "jeffrey E.": "Jeffrey Epstein",
    "john zouzelka-cell": "John Zouzelka",
    "lhsoffic": "LHS Office",
    "lhsoffice": "LHS Office",
    "michael": "Michael Wolff",
    "nate white": "Nate White",
    "nicholas.ribis": "Nicholas Ribis",
    "paul prosperi": "Paul Prosperi",
    "recipient name or email": "Desconhecido (recipient name or email)",
    "rita hortenstine": "Rita Hortenstine",
    "rote": "Desconhecido (rote)",
    "soon yi previ": "Soon-Yi Previn",
    "taal safdie": "Taal Safdie",
    "undisclosed-recipients:": "Desconhecido 23",
    "uri fouzailov": "Uri Fouzailov"
}

In [57]:
df_saida = df_saida.copy()
df_saida.loc[:, 'para'] = df_saida['para'].replace(mapeamento_para)

In [58]:
df_saida = df_saida.drop_duplicates()

In [59]:
df_saida.shape

(2208, 3)

Vamos gerar um json para utilizar numa visualização interativa.

In [62]:
import json

col_de = "de"
col_para = "para"
col_assunto = "assunto"

# Vértices.
grau_series = pd.concat([df_saida[col_de], df_saida[col_para]]).value_counts()

vertices = [
    {"id": pessoa, "grau": int(grau)}
    for pessoa, grau in grau_series.items()
]

# Arestas.
arestas = [
    {
        "remetente": row[col_de],
        "destinatario": row[col_para],
        "assunto": row[col_assunto]
    }
    for _, row in df_saida.iterrows()
]

# Salvar em Json.
with open("grafo_emails.js", "w", encoding="utf-8") as f:
    f.write("const grafo = ")
    json.dump({"vertices": vertices, "arestas": arestas}, f, ensure_ascii=False, indent=2)
    f.write(";")